### ISSUE TITLE
Congratulations @fleadsom for earning your Google Cloud Professional Data Engineer Certification

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#105]
## Who in the FINOS Community would you like to recognise?

Congratulations @fleadsom for earning your Google Cloud Professional Data Engineer Certification and for coming coming 2nd in the UK at the Deutsche Bank 24h global hackathon on Thursday. 

I'm looking forward to seeing your GCP qualification and focus on innovation playing out in [Cloud Service Certification](https://github.com/finos/cloud-service-certification/).

Well done! 👏 💯 💯 💯 

![Screenshot 2021-03-01 at 12 02 07](https://user-images.githubusercontent.com/6029572/109495317-051ea480-7a87-11eb-9cc6-61180b298e69.png)

cc @peterrhysthomas

**Comment by mindthegab** [comment]
Belated congrats @fleasdom! Closing this issue as it's more than 1 YO.
