### ISSUE TITLE
FINOS Community Recognition: Mark Guerriero 

### ISSUE THREAD

**Issue by davidwatkins73** [finos/community#108]
The Waltz team would like to recognize the contributions Mark Guerriero has made to Waltz.  

Mark has contributed several  tutorial videos [1] to help users navigate the features offered by Waltz.  Behind the scenes Mark helps us to coordinate and document the Waltz roadmap.  

Mark also performs an IP review service for all code coming from Deutsche Bank, ensuring that our contributions are free of any potential proprietary information [2].

[1] - The [Waltz YouTube Playlist](https://www.youtube.com/playlist?list=PLGNSioXgrIEfJFJCTFGxKzfoDmxwPEap4)
[2] - Mark's [profile](https://github.com/MarkGuerriero)

**Comment by mcleo-d** [comment]
Thank you @davidwatkins73 for recognising the awesome contribution @MarkGuerriero makes to [Waltz](https://github.com/finos/waltz). I can see through the Waltz commit history that @MarkGuerriero is an active and much valued contributor 🚀 🚀 🚀

It's also great to see a growing backlog of [Waltz educational materials on YouTube](https://www.youtube.com/playlist?list=PLGNSioXgrIEfJFJCTFGxKzfoDmxwPEap4). Thanks @MarkGuerriero and @davidwatkins73 for bringing the FINOS Community on the Waltz journey with you.

![Screenshot 2021-03-09 at 10 34 03](https://user-images.githubusercontent.com/6029572/110457875-05d8bb80-80c3-11eb-8aa0-53a2ae771257.png)
