### ISSUE TITLE
FINOS Q2 2021 All Community Call - April 28th at 10am ET / 3pm BST

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#113]
# FINOS Q2 2021 All Community Call

Join the [FINOS 2021 Q2 All Community Call](https://www.finos.org/hosted-events/2021-04-28-finos-all-community-call) on **April 28th at 10am ET / 3pm BST** where the FINOS team and community will provide updates on what's been happening within the foundation as well as what's coming up. 

We're still working on some of the specifics but we'll definitely be covering the topics below. Register for the FINOS Q2 All Community Call here ... https://www.finos.org/hosted-events/2021-04-28-finos-all-community-call

**Date and Time:** 
April 28th at 10am ET / 3pm BST

**Presenters:** 
Executive Director, Gabriele Columbro aka @mindthegab, the FINOS team and community.

**Topics:**
Some of the items we’ll be covering include:

- Feedback from the Q2 FINOS Governing Board meeting
- Ways to engage with and recognize members of our FINOS community
- Project and community updates and plans

We look forward to seeing you on the call 🚀 

Please feel free to share any topics you’d like us to address by adding a comment to this issue ...

**Comment by stephengoldbaum** [comment]
Hello.  Confirming [morphir](https://morphir.finos.org/) update on the agenda.

-Stephen

**Comment by rikoe** [comment]
Confirming [FDC3](https://fdc3.finos.org/) for the agenda...

**Comment by peter-thomas-db** [comment]
Hi all, confirming [Cloud Service Certification](https://github.com/finos/cloud-service-certification) for the agenda. Cheers, Peter

**Comment by mcleo-d** [comment]
@mindthegab, @toshaellison and @grizzwolf,

The following members of the FINOS community would like to present FINOS Project, SIG or Initiative updates during the FINOS All Community Call on April 28th at 10am ET / 3pm BST 🚀

| Presenters | FINOS Member or Firm | FINOS Project, SIG or Initiative |  FINOS Project, SIG or Initiative Links | Presenter GitHub Profile |
|:----|:----|:----|:----|:----|
| Alvin Shih | Morgan Stanley | KDB+ | <ul><li>https://github.com/finos/kdb</li></ul> | @alvin-c-shih | 
| Amol Shukla | Morgan Stanley | DevOps Mutualization SIG | <ul><li>https://github.com/finos/devops-mutualization</li></ul> | @ashukla13 | 
| Olivier Poupeney | Symphony | Symphony BDK for Java | <ul><li>https://github.com/finos/symphony-bdk-java</li></ul> | @opoupeney | 
| Peter Thomas | Deutsche Bank | Cloud Service Certification | <ul><li>https://github.com/finos/cloud-service-certification</li></ul> | @peter-thomas-db | 
| Riko Eksteen | Adaptive Financial Consulting | FDC3 | <ul><li>https://fdc3.finos.org/</li></ul> | @rikoe |
| Rob Moffat | Deutsche Bank | Symphony Java Toolkit | <ul><li>https://github.com/finos/symphony-java-toolkit</li></ul> | @robmoffat |
| Stephen Goldbaum | Morgan Stanley | Morphir | <ul><li>https://morphir.finos.org/</li></ul> | @stephengoldbaum |

**Comment by beekemarie** [comment]
Also confirming for [Legend](https://github.com/finos/legend).

**Comment by mcleo-d** [comment]
Thank you @beekemarie 🚀 

I have added the Legend update to the FINOS project list above ... 
https://github.com/finos/community/issues/113#issuecomment-818669504

**Comment by agitana** [comment]
hi @mcleo-d posting on behalf of David Ehrich who would like to provide an update on the Reg SIG

**Comment by mcleo-d** [comment]
> hi @mcleo-d posting on behalf of David Ehrich who would like to provide an update on the Reg SIG

Thanks @agitana - I have added @DavidVtFreshAIR and the Innovation Regulation SIG update to the table above - https://github.com/finos/community/issues/113#issuecomment-818669504

**Comment by ffionwiggins** [comment]
Keen to include an update on the Financial Objects Project

**Comment by mcleo-d** [comment]
> Keen to include an update on the Financial Objects Project

Thanks for reaching out @ffionwiggins 🚀  

I have added you to the list of super exciting project updates and will email you a project update template to send back to me.

Have a great day and speak soon,

James.

**Comment by mcleo-d** [comment]
Hi @alvin-c-shih, @ashukla13, @beekemarie, @epsstan, @DavidVtFreshAIR, @oriondean, @ffionwiggins, @opoupeney, @peter-thomas-db, @rikoe, @robmoffat and @stephengoldbaum 👋 

I have added an **Update Slides Merged** column to the FINOS All Community Call presenters table in https://github.com/finos/community/issues/113#issuecomment-818669504 to help guide your updates into the main deck. I will add a .. ✅  .. to let you know your updates have been received and merged 👍 

Thank you @alvin-c-shih and @peter-thomas-db for emailing your updates which have now been merged.

Please let me know how I can help support moving forward.

James 🚀

**Comment by mcleo-d** [comment]
Hi @alvin-c-shih, @ashukla13, @beekemarie, @epsstan, @DavidVtFreshAIR, @oriondean, @ffionwiggins, @opoupeney, @peter-thomas-db, @rikoe, @robmoffat and @stephengoldbaum 👋 

Thank you for your FINOS All Community Call update slides. I have taken what you have provided, have merged them into the main deck and will email everyone on Tuesday with a final update.

Have a great evening and see you at Wednesday's call.

James 🚀

**Comment by ColinEberhardt** [comment]
Thanks for a really good call. @mcleo-d would it be possible to share the slide deck? there are one or two projects we are considering contributing to, so would be useful to have the slides for reference. Thanks.

**Comment by mcleo-d** [comment]
Hi @ColinEberhardt - The slides are currently in the safe hands of @grizzwolf and will be published shortly. I'm really pleased you enjoyed the call 👍  It was great to see 110 attendees at the peak!

**Comment by mcleo-d** [comment]
Hi @alvin-c-shih, @ashukla13, @beekemarie, @epsstan, @DavidVtFreshAIR, @oriondean, @ffionwiggins, @opoupeney, @peter-thomas-db, @rikoe, @robmoffat and @stephengoldbaum 👋

Thank you so much for taking part in such an awesome FINOS All Community Call. I hope you enjoyed the experience of representing your FINOS projects and SIGs with the rest of the FINOS community. The feedback to the FINOS team has been fantastic!

Please remember to raise a [FINOS Community Recognition](https://github.com/finos/community/issues/new?assignees=mcleo-d&labels=community-recognition&template=Community-Recognition.md&title=FINOS+Community+Recognition) for those in your local communities who deserve to be mentioned, as the we're all here to learn and there is a lot to share 🥰 

Have a fantastic week and speak soon.

James 🚀
