### ISSUE TITLE
Rename primary branches to follow best practices

### ISSUE THREAD

**Issue by eddie-knight** [finos/community#114]
Based on the opinions [expressed by GitHub ](https://github.com/github/renaming
) and [within the Linux kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb), it is no longer appropriate to use the term "master" in any situations. As such, it can be safely recommended that FINOS remove any uses of the `master` branch and replace it with the new standard naming convention of `main` for primary branches on each repo.

## FINOS Projects Transitioned
- [ ] Cloud Service Certification - https://github.com/finos/cloud-service-certification

**Comment by mcleo-d** [comment]
Hi @eddie-knight,

Thank you so much for raising this important issue and bringing to the forefront of the FINOS Community.

I have made the FINOS team aware of the recommendation and have also linked your issue to the [#diversity-and-inclusion](https://finos-lf.slack.com/archives/C01EJABAKBN) channel in the [FINOS Slack](https://github.com/finos/community/#join-the-finos-slack) below.

https://finos-lf.slack.com/archives/C01EJABAKBN/p1617709524006800

Thanks once again for opening this important issue 👏 💯 💯 💯 

James.

**Comment by mcleo-d** [comment]
Hi @eddie-knight,

I've added this issue to the FINOS Team Priorities kanban and have discussed the order of work with the team. In April, FINOS has the Q2 FINOS board meeting and All Community Call, so this item will be prioritised for after these events have taken place.

However, I have also added the item to the Cloud Service Certification kanban for discussion with @peterrhysthomas, as we could prioritise for Sprint 2 to document and use as the model for taking forward across all FINOS projects / SIGs thereafter.

Let me know your thoughts?

James.

**Comment by maoo** [comment]
Here's a tutorial on how to rename `master` branch to `main` which I found complete and well written - https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Comment by mcleo-d** [comment]
That's great @maoo - Thanks! 😁

**Comment by mcleo-d** [comment]
This issue has moved forward in Cloud Service Certification by @TLATER here ... 
- https://github.com/finos/cloud-service-certification/issues/119#issuecomment-838280159

**Comment by mcleo-d** [comment]
@TLATER - Thank you for the work done on https://github.com/finos/cloud-service-certification/issues/119 and https://github.com/finos/cloud-service-certification/pull/132 to rename `master` to `main` for [Cloud Service Certification](https://github.com/finos/cloud-service-certification).

Are there any specific lessons learned for FINOS that can be documented that will help other FINOS projects and SIGs follow this lead?

**Comment by TLATER** [comment]
@mcleo-d Yes, I think the main one is to watch out for self-referencing links in the repository :) While those are generally not great practice, it's easy to forget and they'll almost surely pop up.

I believe a `grep -r 'master/'` in the repository should  be enough to find any such links, perhaps while excluding `.git`.

**Comment by maoo** [comment]
Update on this ticket; LFX security have just emailed all teams of FINOS hosted projects with "Non Inclusive Language Alerts".

You can read more on https://docs.linuxfoundation.org/lfx/security/non-inclusive-language

I believe we could rely on LFX Security in order to track non inclusive language across all FINOS Projects.

/cc @alstratigos @agitana

**Comment by maoo** [comment]
Closing this issue, as we have tackled this change across several repositories already; we'll keep on updating names which refer to non-inclusive language. Thanks @eddie-knight !
