### ISSUE TITLE
Make appropriate changes to FINOS Governance to reflect Community Specification approval

### ISSUE THREAD

**Issue by mindthegab** [finos/community#116]
Per our conversation last week, @copiesofcopies will be working early this week on making necessary changes to https://github.com/finos/community/tree/master/governance to:

- [ ] Reflect the approval from the GB of the Community specification
- [ ] Reference the https://github.com/finos/standards-project-blueprint as blueprint for new standards project
- [ ] Deprecate (not delete) existing standard governance and IP policy provisions, setting the stage for us to remove those for good in the next governance overhaul

**Comment by copiesofcopies** [comment]
@mindthegab I've made the required changes to the Standards Project README in [this PR](https://github.com/finos/community/pull/118). 

I also think more changes should be made to the [Blueprint](https://github.com/finos/standards-project-blueprint/) before the documentation will be complete, specifically:
* [Getting Started](https://github.com/finos/standards-project-blueprint/blob/master/..Getting%20Started.md) should instruct projects to clone the blueprint, not the upstream Community Specification repo. The "Best Practices" section should probably also be more opinionated about FINOS's practices.
* I assume the [Scope](https://github.com/finos/standards-project-blueprint/blob/master/2._Scope.md) file should contain the project's approved charter, in which case the file should say that.
* It seems like the [Code of Conduct](https://github.com/finos/standards-project-blueprint/blob/master/8._Code_of_Conduct.md) should be FINOS's CoC.

**Comment by toshaellison** [comment]
Here are a few questions to resolve before making final changes:

**Comment by toshaellison** [comment]
On the last point I've updated the Code Of Conduct in the blueprint to point to FINOS' Code of Conduct.

**Comment by copiesofcopies** [comment]
@mindthegab now that the ISO link has been corrected, I see that there is an example scope statement provided in the document. It's about rice, but I think it's an adequate sample. Based on a review of a number of ISO and other specifications, it appears that scope statements tend to be brief and broad, so I'm less concerned that FINOS contributors need much more detailed guidance.

**Comment by toshaellison** [comment]
I've updated the contact on the FINOS CoC to legal@linuxfoundation.org.

I've drafted the a Standards Project Contribution Template - https://docs.google.com/document/d/1R-WNuT-nEFGbJ4X-HmIsP5IJGXLTHLa0_0b2uzo57wc/edit?usp=sharing

**Comment by toshaellison** [comment]
Mao has reviewed the a Standards Project Contribution Template and I've accepted all changes so I think we're ready to cretae it in GitHub.
