### ISSUE TITLE
Did anyone interested in Financial crime and quantum computing 

### ISSUE THREAD

**Issue by Ivan-Radovanovic** [finos/community#122]
Hello all,
let's share ideas in this areas 

Ivan

**Comment by agitana** [comment]
hi @Ivan-Radovanovic thanks for raising this issue! Participants of the FINOS Open RegTech SIG have previously discussed collaboration opportunities around AML use cases, see https://github.com/finos/open-regtech-sig/issues/17#issuecomment-770087776 for more information.

It would be great to hear more about your interest in AML and quantum computing, feel free to propose this to be added to the [agenda](https://github.com/finos/open-regtech-sig/issues/29) of next week's **Reg SIG meeting** (**Tuesday, June 1st @ 12pm ET / 5pm BST**). Meeting details and agenda are available at https://github.com/finos/open-regtech-sig/issues/29).

You're also welcome to email the FINOS Open RegTech community at open-regtech-sig@finos.org.

/ cc @toshaellison @jgavronsky @ianhollowbread @DavidVtFreshAIR @dehrich123

**Comment by Ivan-Radovanovic** [comment]
Hello @agitana, my schedule for 06/01 is pretty tight and i can not participate but any other days works perfectly  
p.s. thank you  for fast respond

**Comment by robmoffat** [comment]
Hi Ivan,

We're just doing some housekeeping - it seems like @agitana answered this question?  If you would like further discussion on this, feel free to re-open. 

thanks,
Rob
