### ISSUE TITLE
FINOS Q3 2021 All Community Call - July 21st at 10am ET / 3pm BST

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#126]
# FINOS Q3 2021 All Community Call

Join the FINOS 2021 Q3 All Community Call on **July 21st at 10am ET / 3pm BST** where the FINOS team and community will provide updates on what's been happening within the foundation as well as what's coming up. 

[Save the date and register here](https://zoom.us/webinar/register/6016245645034/WN_qNObFDBjR8KLuVzC1tXvlw?__hstc=18943911.2cba9a5eca55736e77e4dcf3e0149ada.1567507898042.1625567698841.1625668970403.532&__hssc=18943911.2.1625668970403&__hsfp=3922412757&hsCtaTracking=84ca6422-6d3a-4370-bc6f-241e96160f85%7Cbd19e4a3-2e95-4b2c-8e1e-698fda8ccf5b) 👈🏻 

We're still working on some of the specifics, so keep an eye on this issue for more updates 👀 

**Date and Time:** 
July 21st at 10am ET / 3pm BST

**Presenters:** 
Executive Director, Gabriele Columbro aka @mindthegab, the FINOS team and community.

**Topics:**
Some of the items we’ll be covering include:

- Feedback from the Q3 FINOS Governing Board meeting
- FINOS Q3 project updates from ...
  - **Legend** - Beeke-Marie Nelke, Goldman Sachs - https://github.com/finos/legend
  - **Waltz** - David Watkins, Deutsche Bank - https://waltz.finos.org/
  - **Symphony BDK for Java** - Olivier Poupeney, Symphony - https://github.com/finos/symphony-bdk-java
  - **Cloud Service Certification** - Peter Thomas, Deutsche Bank - https://github.com/finos/cloud-service-certification
  - **Morphir** - Stephen Goldbaum, Morgan Stanley - https://morphir.finos.org/
  - _Plus more to confirm_

We look forward to seeing you on the call 🚀 

Please feel free to share any topics you’d like us to address by adding a comment to this issue ...

**Comment by mcleo-d** [comment]
This is to confirm @stephengoldbaum and [Morphir](https://github.com/finos/morphir) on the FINOS All Community Call.

**Comment by mcleo-d** [comment]
@mindthegab, @grizzwolf, @agitana and @Julia-Ritter 

The following members of the FINOS community would like to present FINOS Project, SIG or Initiative updates during the FINOS All Community Call on **July 21st at 10am ET / 3pm BST** 🚀

| Presenters | FINOS Member or Firm | FINOS Project, SIG or Initiative |  FINOS Project, SIG or Initiative Links | Presenter GitHub Profile | Update Slides Merged |
|:----|:----|:----|:----|:----|:----|
| Peter Thomas | Deutsche Bank | Cloud Service Certification | <ul><li>https://github.com/finos/cloud-service-certification</li></ul> | @peter-thomas-db | :negative_squared_cross_mark: |
| Stephen Goldbaum | Morgan Stanley | Morphir | <ul><li>https://morphir.finos.org/</li></ul> | @stephengoldbaum | :negative_squared_cross_mark: |
| David Watkins | Deutsche Bank | Waltz | <ul><li>https://waltz.finos.org/</li></ul> | @davidwatkins73 | :negative_squared_cross_mark:  |

**Comment by beekemarie** [comment]
I'll also be there to give an update on Legend https://github.com/finos/legend

**Comment by mcleo-d** [comment]
Hi @beekemarie 👋🏻 

Thank you for registering your interest to present https://github.com/finos/legend.

I have added you to the table above https://github.com/finos/community/issues/126#issuecomment-875464819 and will email regarding the Legend update for the FINOS All Community deck.

James.
