### ISSUE TITLE
Build Community Growth and User Adoption Plans

### ISSUE THREAD

**Issue by brooklynrob** [finos/community#13]
For each program and/or its component projects
* Create/Refine plan for how to build the basis of contributors into the project and/or projects
  * What skill sets are needed?
  * What overall level of commitment (FTEs) are needed to deliver on the roadmap?
  * What support is required/requested from 
     * FINOS Staff?
     * FINOS Board?

* (For programs w/ project in "active" status or approaching activation) create user adoption and product marketing plan to drive usage and consumption
  * What support is required/requested from 
     * FINOS Staff?
     * FINOS Board?

- [ ] DAV
- [ ] DEG
- [ ] DT
- [ ] FDC3
- [ ] FDX
- [ ] FO
- [ ] Hadouken
- [ ] Plexus
- [ ] Symphony
- [ ] Voice

**Comment by brooklynrob** [comment]
@mcleo-d Any update here, especially in regards to our two 2020 focus projects, Perspective (CC @neilslinger) and Plexus (@paulwhitby @lspiro-Tick42)?

**Comment by mcleo-d** [comment]
Hi @brooklynrob 

* Perspective is waiting for @neilslinger to okay an Issue / PR being raised by @mindthegab that will activate the project. @neilslinger's been away from JPMC, so I'm still waiting for the Go-no-Go as we don't want to alert the Perspective team to an unexpected PR arriving into the project.
* The following epic has been created in the Plexus-Interop repo and assigned to @paulwhitby that sets out project activation criteria - https://github.com/finos-plexus/plexus-interop/issues/147. @paulwhitby's on annual leave next week, so @mcleo-d will work with @udalmik on the first parse of the project to highlight growth stories.
* There's an open question around the Plexus API project that's been contributed into the Plexus program by @lspiro-Tick42 and whether that's in scope for this round of activation. I'm currently focused on Plexus Interop with @paulwhitby until that question is answered.

**Comment by mcleo-d** [comment]
Hi @brooklynrob 

Just to update, @mcleo-d and @mikhail are meeting on Monday 17th February at 11am UK to have a first parse at the Plexus activation criteria. 

The output will be stories that fill activation gaps that will roll into discussions with @paulwhitby the following week. 👍 

James.

**Comment by maoo** [comment]
This issue refers to FINOS Programs, which is an entity that doesn't exist anymore. Closing issue.
