### ISSUE TITLE
New York City 9 November - FINOS Member Meeting - Topics and Presenters Wanted!

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#131]
Dear FINOS Community,

This year we're excited to host an in-person **FINOS Member Meeting** in **New York City** and are busy putting together a stimulating agenda of updates, meetings and discussions. 

The Member Meeting in New York City is a unique opportunity for our members to get together and discuss the latest activity across the Foundation and the industry; network with peers from other FINOS Member organizations; and help us drive the direction of open source in financial services.

As we put the agenda together we’re keen to hear from the FINOS Community in two specific ways:

1. Are there specific topics you would like to see covered at the Member Meeting in New York City?
2. Would like to give a presentation or lead a discussion at the New York City Member Meeting? (We’re pretty flexible on format but ask that all topics are relevant and focus on open source in financial services and particularly FINOS projects and standards.)

Please comment on this issue and we look forward to hearing from you and seeing many of you later in the year!

The FINOS Team.

**Comment by mindthegab** [comment]
@maoo how come moving to "Done" doesn't close the issue?

**Comment by maoo** [comment]
AFAIK, it's not how GitHub Boards work. The only automation available is to "move cards on a board when related issues are closed", not the other way around.
