### ISSUE TITLE
London 4 October - FINOS Member Meeting - Topics and Presenters Wanted!

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#132]
Dear FINOS Community,

This year we're excited to host an in-person **FINOS Member Meeting** in **London** and are busy putting together a stimulating agenda of updates, meetings and discussions. 

The Member Meeting in London is a unique opportunity for our members to get together and discuss the latest activity across the Foundation and the industry; network with peers from other FINOS Member organizations; and help us drive the direction of open source in financial services.

As we put the agenda together we’re keen to hear from the FINOS Community in two specific ways:

1. Are there specific topics you would like to see covered at the Member Meeting in London.
2. Would like to give a presentation or lead a discussion at the London Member Meeting. (We’re pretty flexible on format but ask that all topics are relevant and focus on open source in financial services and particularly FINOS projects and standards.)

Please comment on this issue and we look forward to hearing from you and seeing many of you later in the year!

The FINOS Team.

**Comment by mcleo-d** [comment]
Start Time (BST)  | End Time (BST)  | Duration  | Track 1 | Track 2 | Track 3
-- | -- | -- | -- | -- | --
2:10pm | 2:40pm | 30m | To Be Confirmed | Deploying and managing FINOS projects on Hybrid Cloud. Legend Juju Charms Demo and Example. Lead by **Canonical** and Kris Sharma | [KDB+ Project](https://github.com/finos/kdb) Innovation - Developing KDB Studio v2.0 with TypeScript, JavaScript and Electron. Lead by **Scott Logic** and @ColinEberhardt 
2:50pm | 3:20pm | 30m | To Be Confirmed | Accelerating [Waltz](https://github.com/finos/waltz) installation and configuration in your Bank. Lead by **Deutsche Bank** and @davidwatkins73 | Exploring cloud banking platform priorities and challenges with [Cloud Service Certification](https://github.com/finos/cloud-service-certification). Lead by **Deutsche Bank** and @peterrhysthomas
3:20pm | 3:40pm | 20m | PM Break
3:50pm | 4:20pm | 30m | To Be Confirmed | [Timebase CE](https://github.com/finos/timebase-ce) and how banks leverage the open source time series database. Technical deep dive by **EPAM** and @stuartfarr | Accelerating Symphony bot development with [Symphony BDK for Java](https://github.com/finos/symphony-bdk-java/) and [Python](https://github.com/finos/symphony-bdk-python/). Lead by **Symphony** and Kaosar Ahmed 
4:30pm | 5:00pm | 30m | To Be Confirmed | [DevOps Mutualization](https://github.com/finos/devops-mutualization/) - Automated Change Deployment Working Group | Exploring [GitHub Codespaces](https://github.com/features/codespaces) and what this means for open source in banking. Lead by **GitHub**, @peter-murray and @pmanlukas

**Comment by mindthegab** [comment]
Closing this issue. @mcleo-d please make sure you groom these in the future.
