### ISSUE TITLE
FINOS Q1 2022 All Community Call - February 2nd at 11am ET / 4pm UK

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#152]
# FINOS Q1 2022 All Community Call

Reserve the date and join the FINOS 2022 Q1 All Community Call on **February 2nd at 11am ET / 4pm UK** where the FINOS team and community will provide updates on what's been happening within the foundation as well as what's coming up. 

**Register here** - https://zoom.us/webinar/register/8516420111586/WN_SvX-8megSmKbmRgECuez7Q

**Date and Time:** - February 2nd at 11am ET / 4pm UK

Presenters include Gabriele Columbro, FINOS Executive Director aka @mindthegab, the FINOS team and FINOS maintainers from the wider FINOS Community.

During the call you'll hear feedback from the FINOS 2022 Q1 FINOS Governing Board meeting, plus updates from the following FINOS Projects and SIGs ...

- Compliant Financial Infrastructure by Abdullah Garcia, JPMorgan Chase, Vice President
- FDC3 by Kris West, Cosaic, Principle Engineer
- Financial Objects SIG by Ffion Acland, Goldman Sachs, Vice President
- InnerSource SIG by Arthur Maltson, Capital One Director, & Clare Dillon, InnerSource Commons Executive Director
- KDB+ by Alvin Shih, Morgan Stanley, Executive Director
- Symphony BDK/WDK by Olivier Poupeney, Symphony, Director of Developer Relations

Register now to join the FINOS 2022 Q1 All Community Call and we look forward to seeing you on February 2nd.

**Register here** - https://zoom.us/webinar/register/8516420111586/WN_SvX-8megSmKbmRgECuez7Q

**Comment by mcleo-d** [comment]
@mindthegab, @grizzwolf, @agitana and @Julia-Ritter 

The following members of the FINOS community would like to present FINOS Project, SIG or Initiative updates during the FINOS All Community Call on **February 2nd at 11am ET / 4pm UK** 🚀

| Presenters | FINOS Member or Firm | FINOS Project, SIG or Initiative |  FINOS Project, SIG or Initiative Links | Presenter GitHub Profile | Confirmed by FINOS |
|:----|:----|:----|:----|:----|:----:|
| Alvin Shih | Morgan Stanley | KDB | <ul><li>https://github.com/finos/kdb</li></ul> | @alvin-c-shih  | TBC |
| David Watkins | Deutsche Bank | Waltz | <ul><li>https://waltz.finos.org/</li></ul> | @davidwatkins73 | TBC |

**Comment by mcleo-d** [comment]
@davidwatkins73 - I have registered your interest to present at the FINOS All Community Call following the Waltz project meeting below... 

https://github.com/finos/waltz/issues/5813

**Comment by mcleo-d** [comment]
@amaltson and @claredillon - I have registered your interest to present at the FINOS All Community Call following the InnerSource SIG meeting here ... https://github.com/finos/InnerSource/issues/48

**Comment by claredillon** [comment]
Thanks @mcleo-d - looking forward to the community update!

**Comment by opoupeney** [comment]
Happy to give an update on the Symphony developer tools (BDKs/WDK) as well as announcing what is coming up.

**Comment by kriswest** [comment]
Happy to provide a brief update on activity in FDC3 (API additions for 2.0, Contexts and Intents Discussion group, Desktop Agent Bridging discussion group, spec formalisation, etc.)

**Comment by ffionwiggins** [comment]
Keen to have an update on the Financial Objects SIG and highlight some of the ongoing projects to spark interest and expand the groups

**Comment by mcleo-d** [comment]
Hi @abdullahgarcia - I have added you to the table above following our recent call. 

Kind regards, 

James 🚀

**Comment by robmoffat** [comment]
Hi, we'd like to give an update on Spring Bot please.  thanks!

**Comment by mcleo-d** [comment]
> Hi, we'd like to give an update on Spring Bot please. thanks!

Hi @robmoffat - The agenda for the Q1 2022 All Community Call has now been finalised. It would be awesome to catch up regarding what can be done through other FINOS channels and SIGs.

Speak soon,

James 🚀

**Comment by robmoffat** [comment]
ok no worries, James.  I missed the email about this - my bad

**Comment by mindthegab** [comment]
Great all community call once again - thanks @mcleo-d for organizing and to all the project maintainers for the lively participation! We had over 140 people join and that's an amazing leading indicator of a fantastic 2022!

Take a look at the recap and recording here https://www.finos.org/blog/finos-q1-2022-all-community-call-wrap-up.
