### ISSUE TITLE
Rename "Symphony Java Toolkit" project to "Spring Bot"

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/community#158]
The symphony-java-toolkit repo has been renamed to [spring-bot](https://github.com/finos/spring-bot). 

Questions:
- [x] Name spring-bot vs symphony-spring-bot?

Follow up tasks:
- [x] Readme
  - [x] Title should be project name
  - [x] Mention multi-chat bot (supports Symphony and Microsoft Teams)
- [x] Ensure [Project Blueprint](https://github.com/finos/software-project-blueprint) template is followed. https://github.com/finos/spring-bot/pull/295
- [x] New Logo - `Update the name ; use font and color that differs from other Symphony logos`
  - [x] Deploy to Landscape.
  - [x] Update category and sub-category(?) on the FINOS landscape (@maoo may propose to put it into `Data & Business Logic > Frameworks`)
- [x] Website upates. [springbot.finos.org](https://springbot.finos.org)
- [x] Create Jira Ticket to LF in order to update SFDC (SS JIRA project)
  - [x] Send logo to Mindy (https://jira.linuxfoundation.org/browse/SS-636)

**Comment by TheJuanAndOnly99** [comment]
@maoo SpringBot team is deliberating on logo changes.

**Comment by maoo** [comment]
All done, thanks @TheJuanAndOnly99 !
