### ISSUE TITLE
Typo on in consume link on community.finos.org

### ISSUE THREAD

**Issue by vmbrasseur** [finos/community#181]
Spotted by Kat Novakovic:

> Hello,
> 
> On https://community.finos.org, I spotted a small typo: 
In the 'OSS Journey' section, the 'consumption' link goes to https://community.finos.org/docs/journey/cosume instead of https://community.finos.org/docs/journey/consume .
> 
> Kat

**Comment by mindthegab** [comment]
Thanks @vmbrasseur (and Kat!) - this is now fixed. 

For the future, FYI, each page of the website is easily editable (there's an edit button at the bottom) so in case you feel like you can easily raise a PR to fix these typos. 

We put a lot of effort in moving all Community related content in Github to enable just that.
