### ISSUE TITLE
Standardizing microsite footers

### ISSUE THREAD

**Issue by psmulovics** [finos/community#184]
Right now each microsite (like https://osr.finos.org/ or https://odp.finos.org ) has a different footer (footer.js) content.

ODP:
> FINOS Projects
> [FINOS Landscape](https://landscape.finos.org/)
> [FINOS Projects on GitHub](https://github.com/finos)
> [Collaboration Infrastructure](https://community.finos.org/docs/collaboration-infrastructure)
> FINOS Governance
> [Community Governance](https://community.finos.org/docs/governance/intro)
> [FINOS Charter](https://community.finos.org/docs/governance/charter)
> [Meeting Procedures](https://community.finos.org/docs/governance/meeting-procedures)
> About FINOS
> [FINOS Website](https://www.finos.org/)
> [Engage the FINOS Community](https://www.finos.org/engage-with-our-community)
> [FINOS News and Events](https://www.finos.org/news-and-events)

OSR:
> Docs
> [Team](https://osr.finos.org/docs/team)
> [Roadmap](https://osr.finos.org/docs/roadmap)
> FINOS
> [FINOS Website](https://www.finos.org/)
> [Community Handbook](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/80642059/Community+Handbook)
> [Community Governance](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530783/Community+Governance)
> More
> [Follow @FinosFoundation](https://twitter.com/FinosFoundation)
> [FINOS on LinkedIn](https://www.linkedin.com/company/finosfoundation)

My suggestion would be to have a standardized footer as part of one of the main finos repos, in a separate branch, with the ability to git submodule that footer.js file into the individual repos containing the microsites.

**Comment by mindthegab** [comment]
Thanks @psmulovics - we did retire odp.finos.org which now points at https://community.finos.org/docs/collaboration-infrastructure/. 

That said I think your suggestion definitely stands - @maoo or @mcleo-d do you think this is something we can add to our blueprint and then git submodule from there?

**Comment by maoo** [comment]
It's definitely doable. An alternative solution to git sub module is to fetch the file (via http) during the node build (one one change in package.json). Such change could be contributed to the project blueprint, so that new website would come up with the "common FINOS footer".

One question is about the footer color: should that be still configurable, given that not all FINOS microsites have the same color palette?

As soon as we align on this, we can prioritize the issue and get to work. TY!

**Comment by maoo** [comment]
Sorry for the late reply on this; we've discussed this further at FINOS, and given that:
- most of Docusaurus V1 websites have been moved to V2
- odp.finos.org is now deprecated in favour of community.finos.org
- we see that often microsites use different footers (maybe with some links in common)
- we have https://github.com/finos/software-project-blueprint which already provides a common setup (and we're happy to evaluate improvements there)

we think that this change - which may require quite some engineering effort - is not a priority right now for the FINOS team.

We could still keep it open with the `Help wanted` label, just in case some new contributor wants to pick it up, but given all current activities at FINOS, we find difficult to allocate time for this.

**Comment by maoo** [comment]
Moved issue to https://github.com/finos/software-project-blueprint/issues/62
