### ISSUE TITLE
2020 Project Roadmaps

### ISSUE THREAD

**Issue by brooklynrob** [finos/community#19]
Focus for 2020 should roadmaps at the *project* level first and foremost, with as needed roll-ups and interdependencies between projects to the program level.

Check list below should be used to reflect when all of the projects in a program have completed their draft project level roadmaps for 2020.

**2020 Roadmap DRAFT**
- [ ] DAV
- [ ] DEG
- [x] DT
- [x] FDC3
- [ ] FDX
- [x] FO
- [ ] Hadouken 
- [x] Plexus
- [ ] Symphony
- [x] Voice

**Comment by maoo** [comment]
This issue refers to 2020 roadmap. Given that we're in 2021, we can safely close the issue.
