### ISSUE TITLE
FINOS Q4 2022 All Community Call - Wednesday October 26th at 10am EST / 3pm BST

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#209]
# FINOS Q4 2022 All Community Call

Register to join the **FINOS 2022 Q4 All Community Call** on **Wednesday October 26th at 10am EST / 3pm BST**, where Gabriele Columbro, FINOS Executive Director, and the FINOS team will provide updates from the FINOS Q4 Governing Board Meeting. 

**Date and Time:** 
October 26th at 10am ET / 3pm BST

Register here - https://zoom.us/webinar/register/1916651496047/WN_FOGWP6HsT-6BvL6XMHUH_w

Register now for updates including Getting Ready for OSFF New York, Latest FINOS Resource Centre Additions and FINOS Project Updates!

Join the FINOS 2022 Q4 All Community Call and we look forward to seeing you on **Wednesday October 26th at 10am EST / 3pm BST**.

Register here - https://zoom.us/webinar/register/1916651496047/WN_FOGWP6HsT-6BvL6XMHUH_w

**Comment by mcleo-d** [comment]
@alvin-c-shih to join the FINOS All Community Call to pitch the idea of MLOps projects to the FINOS community.

**Comment by mcleo-d** [comment]
@stephengoldbaum - to join the FINOS All Community Call to update on Morphir and the LCR contribution from Morgan Stanley

**Comment by mcleo-d** [comment]
@sndpkumar14 and Tim Norman - to organise a Compliance Horizon Scanning one slide overview for the FINOS All Community Call.

**Comment by maoo** [comment]
🙋 - for a quick update on FINOS Security Scanning - https://github.com/finos/security-scanning
