### ISSUE TITLE
Recategorize `voice-metadata-standard` project as 'incubating'

### ISSUE THREAD

**Issue by tschady** [finos/community#21]
The official record for `voice-metadata-standard` should be updated from Operating -> Incubating

The project is in 'incubating' now, that has been reflected on the readme for months, https://github.com/finos/voice-metadata-standard.

**Comment by brooklynrob** [comment]
Thanks @tschady. @mindthegab and I are looking through the metadata right now will also get this updated in the metadata.

**Comment by tschady** [comment]
just apply this patch and it should do it.  (this diff is against an older `metadata` repo I used to have access to)


[patch.txt](https://github.com/finos/finos-pmcs/files/4047538/patch.txt)

**Comment by mcleo-d** [comment]
Issue updated and closed.
