### ISSUE TITLE
Pronunciation

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/community#210]
I feel this is an important issue to resolve, and requires immediate attention. Just how is FINOS supposed to be pronounced?

I've heard the following:

- Fee-nos (rhyming with fee)
- Fin-os (rhyming with fin)
- Fin-oh-es (spelling out the O and S as in operating system)

Which is right?!

Thank you for your attention.

**Comment by robmoffat** [comment]
@maoo  and I just discussed this:

Number 2 in preference.  Number 3 is definitely wrong.

**Comment by robmoffat** [comment]
please reopen if you have any other questions!
