### ISSUE TITLE
FINOS Community Leadership Award Nominations - OSFF New York 2022

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#213]
## Nominate Your FINOS Community Leadership Award Candidate

FINOS invites you to nominate your **FINOS Community Leadership Award** candidate for the award that will be presented at the [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-new-york/), New York City on **8th December 2022**.

The nominated person **must work in the Americas** and their **name**, **firm**, **role** and **case for their nomination** must be clearly stated in the comments using the questions below as a guide ... 

1. Name and Job Title of nominee
2. Why have you nominated this person?
3. What differentiates this individual from the others in the FINOS Community?
4. What is the one big impact this individual made in FINOS and FINOS Projects?
5. Is there anything else you’d like to mention?

The person and their firm must be available to collect the award at OSFF on 8th December in New York City. Please register for OSFF, NYC here ... https://events.linuxfoundation.org/open-source-finance-forum-new-york/

The winner will be selected by the [FINOS Diversity, Equity and Inclusion SIG](https://github.com/finos/DEI-SIG), so please make your nominations descriptive, compelling and provide as much evidence as possible. 

**Award nominations close on Friday 18th November 2022**

**Comment by mcleo-d** [comment]
I would like to recognise Ivan Radovanovic, Financial Crime Investigator at Citizens Bank, for promoting FINOS and open source ways of working at Citizens Bank.

Ivan uses his free time to participate in tech sprints and open source initiatives to find missing persons all around the world using open source. Ivan also led an anti-CSAM tech sprint team through FINOS Regulation Innovation and AIR to help protect children from online predators.

At Citizens Bank, Ivan has started numerous initiatives and submitted ideas with examples of how open source can help with the bank's daily work and their financial crime investigations.

Ivan attends FINOS Community Calls and helps magnify FINOS social media by liking, sharing and reposting to spread the great work of the FINOS Community and to further promote FINOS Projects and SIGs.

**Comment by Ivan-Radovanovic** [comment]
> I would like to recognize Ivan Radovanovic (@Ivan-Radovanovic), Financial Crime Investigator at Citizens Bank, for promoting FINOS and open source ways of working at Citizens Bank.
> 
> Ivan uses his free time to participate in tech sprints and open source initiatives to find missing persons all around the world using open source. Ivan also led an anti-CSAM tech sprint team through FINOS Regulation Innovation and AIR to help protect children from online predators.
> 
> At Citizens Bank, Ivan has started numerous initiatives and has submitted ideas with examples of how open source can help with the bank's daily work and their financial crime investigations.
> 
> Ivan attends FINOS Community Calls and helps magnify FINOS social media by liking, sharing and reposting to spread the great work of the FINOS Community and to further promote FINOS Projects and SIGs



Thank yo so much James it means a lot to me
