### ISSUE TITLE
Most of the times website build fails with "no content change" even if content was changed

### ISSUE THREAD

**Issue by mindthegab** [finos/community#221]
Most [Community site deploys](https://app.netlify.com/sites/eager-borg-83c1a5/deploys) fail with "no content change" even thought there's a content change - so often time I have to resort making clerical changes in the docusaurus.config.js to trigger a real rebuild.

Not sure if this is fixable but would be nice to to have to hack / work around this. Thanks!

**Comment by maoo** [comment]
Thanks for raising this @mindthegab !

Found this https://answers.netlify.com/t/builds-cancelled-for-a-new-branch-due-to-no-content-change/17169/2 

I applied the fix and it seems that it works, see https://github.com/finos/community/commit/94ccfe06523743669f15bc7b49007c5f76d41fe8

@robmoffat @mcleo-d  - FYI, as I feel that you had the same issue on FDC3 and other projects.

Closing the issue now, please reopen if you see it happening again.
