### ISSUE TITLE
Support multiple meetings / working groups / teams per project

### ISSUE THREAD

**Issue by mindthegab** [finos/community#23]
FINOS team will discuss and report back how to support this use case.

As per original request from @rikoe below:

I would like to request that the new proposal for project at the top level still support the idea of multiple "working groups" or "teams" per project, which would correspond to different sub-teams that cover particular disciplines.

E.g. in FDC3, we are working on the same project, and in the same repository in GitHub, but the "API team" and the "Use Case team" have separate meeting times and mailing lists, as not everything covered in every meeting is relevant for everyone.

I view this as, for example during a large software development project, while one project, you might have multiple chat channels/email groups, e.g. for the UI team, the server team and the DevOps team.

I expect this to be the exception, not the rule, but it will be great if the new project model can support such a structure, even if it is mostly self-governed by each project. I think the easiest way to accomplish this is via GitHub sub-teams for the project, and email/chat setup to correspond to the GitHub teams.

_Originally posted by @rikoe in https://github.com/finos/finos-pmcs/pull/22#issuecomment-573675240_

**Comment by robmoffat** [comment]
Seems like this has been resolved now:

 - We have multiple tracks of discussions going on in the GitHub discussions board: https://github.com/finos/FDC3/discussions
 - We have multiple tracks of meetings (CD&I, Desktop Bridging, API, Maintainers) each with their own agenda issues in GitHub
 - We have multiple mailing lists - fdc@finos.org, fdc3-maintainers@finos.org, fdc3-participants@finos.org. fdc3-context-intents@finos.org

@rikoe please re-open this issue if you think there's anything we're missing here, or could do better.

@maoo
