### ISSUE TITLE
Morphir Project Activation

### ISSUE THREAD

**Issue by stephengoldbaum** [finos/community#230]
# Activation
Virtually all FINOS hosted projects are expected to strive towards, and ultimately attain, [Active status](https://community.finos.org/docs/governance/Software-Projects/stages/active) and the related badge. An active badge indicates to potential consumers that the project has reached a level of maturity, both functional and non-functional, that it is suitable for production use.

The [Technical Steering Committee](https://github.com/finos/technical-steering-committee) approves lifecycle transitions following objective criteria detailed in the below checklist. More information in the [FINOS Governance](https://community.finos.org/docs/governance/#project-lifecycle).

### What does activation mean for the consumer? 
:heavy_check_mark: The Project is high quality, mature from a codebase and community dynamics perspective. 

:dart: The Project produces valuable releases to solve a useful business problem for our Community.

### What does activation mean for the project team?
:star: Glory in the Community 

:eyes: :loudspeaker: Increased visibility and positioning in FINOS web resources, marketing and Community building efforts like meetups, blog posts, etc.

# Activation Checklist
|  | **Activation (promotion to Active State)** | How and Where Demonstrated | Validated |
|:------ |:----------- |:----------- |:-------
|  | **QUALITY & SECURITY** |   |
| **Development Process** | <p>The Project adopts best-of-breed standards of distributed software development, including but not limited to:</p><ul><li>semantic versioning</li><li>tagging / branch protection</li><li>continuous integration ("CI") and continuous delivery ("CD") where applicable</li></ul><p>If Project Team choses not to use the FINOS provided Open Developer Platform (ODP), a comparable SDLC should be adopted and made available.</p> | The Morphir projects employ automated semantic versioning, continuous integration, and automated publishing to Maven, Elm, and NPM package managers. [More Info](https://github.com/finos/morphir/blob/main/docs/versioning.md)| Yes |
| **Build & Release** | <p>The Project code/documentation release process automated or at lest well documented.</p><p>If code is published, publicly redistributed release binaries should be listed or referred to in the documentation (e.g. under the FINOS namespace in an artefact repository or package manager, e.g. NPM, Maven Central, etc.)</p> | [Fully documented release and publishing.](https://github.com/finos/morphir-jvm/blob/main/docs/release.md) | Yes |
| **Security** | <li>The project has an [OpenSSF "Passing" badge](#obtaining-the-openssf-best-practices-badge) </li> <li>Maintainers are familiar with the [FINOS Security vulnerabilities responsible disclosure](../cve-responsible-disclosure)</li><li>An automated security scanning tool is enabled on the project (e.g. [FINOS Security Scanning](https://www.finos.org/blog/introducing-finos-security-scanning) or [WhiteSource](/docs/development-infrastructure/code-validation/whitesource))</li> |Passed the FINOS badge requirements| Yes |
| **Documentation** | <p>The README.md must include or reference up to date:</p><ul><li>end user docs, including a description of the software, feature overview, installation & configuration instructions</li><li>developer docs, including links to other external systems (further docs, wiki, CI & validation tools, artefact repository, change log / history, etc.)</li><li>where possible badges (e.g. from shields.io) are encouraged</li><li>sample code explaining how to use the project, library, standard, SDK, etc.</li></ul> | Plenty of documentation. The best starting point is [Landing Page](https://morphir.finos.org) | Yes |
|  | **DIVERSITY & VIABILITY** |       |
| **Community** | Project has active participation from 2+ independent individuals and/or organizations; Ideally Project Team members who make contributions in connection with their employment are doing do as part of their regular job duties. | Morphir has maintainers from Morgan Stanley and Capital One. There are also contributions from Microsoft, Codethink, Databricks, and more in the works. | Yes |
| **Project Team** | Project Team has/have demonstrated active involvement commitment to the open source project | The Morphir project has been one of the most active FINOS projects  for a few years.| Yes |
| **License** | Project must not have dependencies which effectively restrict how the project may be distributed or deployed and must not depend on any proprietary third-party components for their core functionality. | No prohibitive dependencies | Yes |
| **Trademark** | Community is using a different established Project name or original contribution trademark is owned by FINOS. All Project related websites and assets are owned and hosted by FINOS. | Yes | Yes |
|  | **ROADMAP & RESOURCES** |       |
| **Progress** | Project has progressed against its public roadmap during incubation. | It has | Yes |
| **Versioning** | Project software is production grade and ready for large scale consumption. 1.0.0 version was released and announced it to the announce@ mailing list. | It is currently being used in production at two financial firms. | Yes |
| **Roadmap** | Projects share and work to a public roadmap. | The full roadmap is managed in GitHub Discussions, Issues, and Projects. |  |
| **FINOS Support** | Project Team is largely self-sufficient, requiring minimal operational support from FINOS to govern and maintain the project. FINOS support switches to strategic growth of the Project in the Community. | Check | Yes |
|  | **GROWTH & ADOPTION** |       |
| **Usefulness** | The Project demonstrably solves a real life use case in the Community. Evidence of adoption beyond the contributing individuals or firms (e.g., in the form of download statistics, listing known deployments or implementations, etc.) | The FINOS open-source version is used in production at financial firms . It also is basis for FINOS Open Reg Tech initatives. |
| **Status Badging** | Project Team commits to adopt the FINOS Active badge in the README.md once the FINOS team approves activation, in order to properly signal  the new Project Lifecycle status to adopters. | Check | Yes |
|  | **HYGIENE & OPERATIONS** |       |
| **Compliance** | The appropriate license text is included in each source file's header. See details and template | Check | Yes |
| **Community Inquiries** | Community inquiries on the project channels (mailing lists, issues and pull requests, etc) are generally promptly answered | They are .  | Yes |
| **Meeting Hygiene** | If the project meets regularly on-line, the Project Team has demonstrated a track record of publishing and distributing agenda no less than 24 hours before the meeting, and publishes meeting minutes after calls. | Fortnightly meetings | Yes |
| **Transparency** | Project Team has adopted a transparent governance model(*) consistent with FINOS Community governance. Work for new contributors is organized into issues within a public issue tracking system, as appropriate, tagged as "Good First Issues" | All governance is accessible on GitHub | Yes |

_(*) transparent governance model is when a project’s discussions, minutes, deliberations, project plans, issue tracking plans for new features, and other artefacts are open, public, and easily accessible in the FINOS Project Infrastructure or FINOS sanctioned external system._

**Comment by eminty69** [comment]
Summary of findings from TSC review

**Usefulness** : Morphir has a clear business problem that its addressing. This is covered at length in the product documentation, including the history of why it was developed in the first case.  The documentation covers use cases, in particular RegTech, and Morphir related use cases are amongst those included in the FINOS / BMO hackathon. Examples are easy to find and clearly documented.
 
**Community** : Work on Morphir is done in the public domain with regular calls and minutes on github. While Morgan Stanley is the main contributor, other individual and companies, eg Capital One, are engaged.  There is also a slack channel – I don’t have access to Slack at work so can’t comment on how widely its used.  There are clear instructions on how to install Morphir and how to contribute to it.

**Progress**: Morphir is made up of a number of separate git repos.  There is active contributions to these as well as minuted meeting notes that relate to topics on the roadmap. However, the roadmap itself lacks detail. Once activated, ideally the roadmap would be elaborated, providing more detail around future features (with rough dates), giving greater opportunity for collaboration.

**Comment by TheJuanAndOnly99** [comment]
Project is "active". @stephengoldbaum to send email to annouce@finos.org before we close the issue.

**Comment by maoo** [comment]
Announcement sent out, see https://groups.google.com/a/finos.org/g/announce/c/_jqX0w9TwQA/m/jJJ82QOeBQAJ

Congrats @stephengoldbaum and the entire Morphir team!
