### ISSUE TITLE
Create badge for FINOS labs

### ISSUE THREAD

**Issue by mindthegab** [finos/community#233]
Hey @maoo @mcleo-d, very much like we have for [forming, incubating, active and archived projects](https://community.finos.org/docs/governance/software-projects/project-lifecycle/), can we create a badge for projects that are in FINOS labs? 

That way we could also start having labs projects in the landscape for example or at least have a clear way to reference labs projects in a visual way and in our lifecycle.

Thanks

**Comment by maoo** [comment]
@mindthegab - couldn't / shouldn't we consider labs a formation stage?
