### ISSUE TITLE
Bot Working Group: Discuss and Form?

### ISSUE THREAD

**Issue by robmoffat** [finos/community#235]
This is a placeholder as I wasn't sure which template to use for working groups.

- Currently, the DB guys and I have a Spring-bot catch up every Wednesday.  
- Symphony also have multiple internal meetings for their FINOS projects.

@opoupeney and I discussed that now that Symphony are becoming maintainers of spring-bot, we would combine all this into a single twice-monthly bot working group meeting.

WDYT?

**Comment by maoo** [comment]
Like the idea @robmoffat ! We could provision you a Zoom account, so that you can share meeting management across the Spring Bot and Symphony maintainers; would you be interested in that?

In parallel, could you engage with Spring Bot and Symphony teams to ask time/date availability? At that point we should be pretty much set!

**Comment by jstclair2019** [comment]
Sounds great, are we just focused on bots or would we broaden it to bots and RPA? Just noodling :)

**Comment by opoupeney** [comment]
Bots are more generic. RPA can be achieved by headless bots and WDK the right tool for that.

**Comment by jstclair2019** [comment]
👍🏻👍🏻

**Comment by maoo** [comment]
@robmoffat - any update on this? Do we have a proposed time/date for the meeting?

I would also suggest to update the issue title, since "Working Group" may suggest that we need to create a new FINOS body, whereas I think that this is just about organizing a cross-initiative recurrent meeting.

TY.

**Comment by maoo** [comment]
First meeting will happen on Tuesday 28 of March. Closing issue. TY @TheJuanAndOnly99 and @robmoffat !
