### ISSUE TITLE
Update governance / contribution process documentation to reflect TOC 

### ISSUE THREAD

**Issue by mindthegab** [finos/community#275]
Assuming the TOC is approved next week, based on [the approved governance](https://github.com/finos/technical-steering-committee/discussions/72) our web properties need an update, specifically:

 
- [x] Replace TSC with TOC (new name)
- [x] Rename tsc@lists.finos.org to toc@lists.finos.org
- [x] [Charter text version](https://community.finos.org/docs/governance/charter) needs to be updated - @jgavronsky can provide -  https://github.com/finos/community/pull/279
- [x] [Charter PDF version](https://www.finos.org/hubfs/FINOS%20Charter.pdf) needs to be updated - @jgavronsky can provide/action - Niamh uploading PDF to hubspot
- [x] The [TOC governance (responsibilities and elections)](https://github.com/finos/technical-steering-committee/discussions/72) should be single sourced, probably in the readme of the TOC repo (/cc @ColinEberhardt) and then referenced from all the other resources (rather than duplicating) => _https://github.com/finos/technical-oversight-committee/blob/master/responsibilities.md and https://github.com/finos/technical-oversight-committee/pull/78_
- [x] A reference / section for TOC should be added to the [governance overview](https://community.finos.org/docs/governance/) page and / or create a dedicated page under "governance" (sibling of "governing board")  => _https://github.com/finos/community/pull/278_
- [x] [Software project governance](https://community.finos.org/docs/governance/Software-Projects/contribution) needs a overhaul to reflect the TOC approves open source projects, while the board approves SIGs and open standard projects. That might impact (reduce) the need for pre-socialization, which was in fact a proxy for not having a TSC. => _https://github.com/finos/community/commit/f20e54480a819c57ab65a0a48ea02dbd94d7b46e_
- [x] The [lifecycle](https://community.finos.org/docs/governance/Software-Projects/project-lifecycle) pages should reference that the TOC owns transitions now => _https://github.com/finos/community/commit/5eba889ddf6449c766b7f48288c614639b4cb8ad_
- Potentially, the new contribution / activation / archival issues should now be moved to this repo, https://github.com/finos/technical-steering-committee, so they go straight in the TOC visibility. => _I feel that this deserves a dedicated issue, as there may be several pointers to update. At the same time, I don't see a lot of rush in doing it right now._
-  The [lifecycle](https://community.finos.org/docs/governance/Software-Projects/project-lifecycle) pages should probably point people to opening issues to the [TOC repo](https://github.com/finos/technical-steering-committee) if they want to propose changes to the lifecycle
- [x] The [TSC repo](https://github.com/finos/technical-steering-committee) should be renamed to 'technical-oversight-committee' or 'toc'
- In the website [governance page](https://www.finos.org/governance) we should probably add a "TOC" section under "Community Governance" => _this seems to be a duplicate of item number 5 of this list_
- [ ] @alstratigos to add TOC Chair to governing board lists and webpage

Let's get this done throughout August plz.

**Comment by ColinEberhardt** [comment]
Here's a PR that implements the name change for the TOC repo: https://github.com/finos/technical-steering-committee/pull/77

**Comment by maoo** [comment]
All done on our end!

@alstratigos - could you please coordinate adding the TOC Chair to governing board lists and webpage?

**Comment by alstratigos** [comment]
Sure, @maoo   
@ColinEberhardt - Is CTO, Scott Logic your exact title?  We will also list you as Chair, FINOS Technical Oversight Committee.
Also, please provide the bio & headshot you'd like us to use on the [FINOS GB page](https://www.finos.org/governing-board).

**Comment by alstratigos** [comment]
@winmorgan @niamhoparker   Do we have a recent headshot/bio for Colin that we can use?  He's on holiday for a few weeks but we can get this up on the website and he can make any changes when he returns.

**Comment by niamhoparker** [comment]
we could use his linkedin image? created asana task here > @winmorgan https://app.asana.com/0/1204390893339905/1205195892265567/f

**Comment by niamhoparker** [comment]
@winmorgan - please use this profile image instead which we've used in the past pls > https://osffnewyork22.sched.com/speaker/ceberhardt3

**Comment by winmorgan** [comment]
Updated

**Comment by alstratigos** [comment]
@ColinEberhardt   You are now listed on the[ FINOS Governing Board page](https://www.finos.org/governing-board)
Please provide your most recent bio and we'll add that as well.

**Comment by ColinEberhardt** [comment]
We need to remove or update the following page:

https://github.com/finos/technical-oversight-committee/blob/master/voting.md

**Comment by maoo** [comment]
> We need to remove or update the following page:
> 
> https://github.com/finos/technical-oversight-committee/blob/master/voting.md

@ColinEberhardt - I'd suggest to keep it, in order to document the TOC voting process (for TOC members, FINOS Staff and the wider community); what changes would you suggest?

**Comment by ColinEberhardt** [comment]
OK, happy to keep it there.

> what changes would you suggest?

I'd assumed the voting rules had been copied into the FINOS governance documentation, and the two needed to be kept in synch. Happy to keep the voting rules in the TOC repo 👍

**Comment by maoo** [comment]
> OK, happy to keep it there.
> 
> > what changes would you suggest?
> 
> I'd assumed the voting rules had been copied into the FINOS governance documentation, and the two needed to be kept in synch. Happy to keep the voting rules in the TOC repo 👍

We only added a mention to the TOC into the community.finos.org page that describes FINOS governance, but we didn't add voting details. Also, `voting.md` is linked from https://community.finos.org/docs/governance/#technical-oversight-committee .

**Comment by maoo** [comment]
All done, https://www.finos.org/governing-board updated. Closing issue.
