### ISSUE TITLE
Software Project Contribution and Onboarding: TraderX

### ISSUE THREAD

**Issue by DovOps** [finos/community#277]
Please note that only FINOS members can propose new projects. If you're interested in membership, see https://www.finos.org/membership-benefits#become-a-member.

# Onboarding Process

Completing an onboarding of a project into FINOS requires following these 5 main steps:  

1.  [**Describing the Contribution**](#1-describing-the-contribution) _led by contributor_
2.  [**Approval**](#2-approval) _led by FINOS TSC_
3.  [**Preparing for Onboarding**](#3-preparing-for-onboarding) _led by contributor_
4.  [**Onboarding**](#4--finos-onboarding) _completed by FINOS Infra_
5.  [**Announcement**](#4--finos-onboarding) _led by FINOS Marketing_

# 1. Describing The Contribution

TraderX is a sample trading application, meant to be a usable simple yet distributed reference application in the financial services domain which can be used for experimenting with various techniques and other open source projects. It is designed to be simple and accessible to programmers of all backgrounds, and can serve as a starting point for educational and experimentation purposes.

It is designed to be runnable from any developer workstation with minimal assumptions other than Node, Java and .NET (Core) runtimes.

## Business Problem
In financial services domain, and FINOS in particular, there are sometimes challenges in illustrating concepts/ideas concretely when it comes to new/existing open source projects in a way which is relevant to the domain.  Often project promoters need to create their own reference application to better demonstrate the value their project is creating. 
 
## Proposed Solution
TraderX is a sample trading application, meant to be a usable simple yet distributed reference application in the financial services domain which can be used for experimenting with various techniques and other open source projects. It is designed to be simple and accessible to programmers of all backgrounds, and can serve as a starting point for educational and experimentation purposes. By having a simple shared sample application, it will be easier to demonstrate various projects and ideas in FINOS and financial services overall by creating an example which integrates their project onto a forked copy/instance of this sample application. By using the same sample application for each integration, the audience will easily understand the demonstration, being already familiar with the underlying reference application being used.

## Tentative Roadmap
Initial goal is to move the project and its assets over to FINOS from finos-labs.  From there we should set up the appropriate CI jobs and create the option for developers/experimenters to spin this up in a FINOS hosted developer environment.
 
## Current State
All code and documentation can be found at https://github.com/finos-labs/traderX
 
## Existing Materials

 - [x] GitHub Repository
   - [x] URL for the repository:  https://github.com/finos-labs/traderX
   - [x] Project Name: traderX
   - [x] @finos-admin has been given read-only permissions if private (N/A)
 - [x] Is Continuous Integration used? No
 - [x] Was the project ever released? No
   - [x] If so, are releases public? N/A 
   - [x] And what's the latest released version? N/A
 - [x] Existing Project Documentation All code and documentation can be found at https://github.com/finos-labs/traderX

 - [x] Does the name have a registered trademark? No
 - [x] Is there a logo? No
 - [] High-Level Presentation prepared for Technical Steering Committee _(~15 mins)_
 - [ ] Are meetings currently held for the project? _(yes / no + details)_
 - [ ] Are meeting minutes, agenda and attendance tracked? _(yes / no + details)_

### Maintainers
*Who will be the [project maintainer(s)](https://odp.finos.org/docs/finos-maintainers-cheatsheet/#maintainer-responsibilities-and-available-resources)? Provide full name, affiliation, work email address, and GitHub username.*

|Name                        |Affiliation              |Work Email Address             |Github username              |
|----------------------------|-------------------------|-------------------------------|--------------------------------------|
|Dov Katz                |Morgan Stanley              |dov.katz@morganstanley.com               |@dovops                      |
|Cliff Tiltman                |Morgan Stanley              |clifford.tiltman@morganstanley.com               |@ctiltman                       |

### Confirmed contributors
*If applicable, list all of the individuals that have expressed interest in and/or are committed to contributing to this project, including full name, affiliation, work email address, and GitHub.com username*

|Name                        |Affiliation              |Work Email Address             |Github username              |
|----------------------------|-------------------------|-------------------------------|--------------------------------------|

### Target Contributors
*Describe the contributor profile (background, position, organization) you would like to get contributions from.*

## Project Communication Channel(s)

- [x] Contributor to ask maintainers which communications channels they'd like to use:
- Asynchronous
  - [x] GitHub Issues _(public)_
  - [x] GitHub Discussions _(public)_
- Synchronous
  - [x] Recurring meetings

## Understanding FINOS Onboarding Requirements

As a project onboarding into FINOS, you will need to familiarize yourself and your contributor team with the following materials:

 - [FINOS overview](https://www.finos.org/hubfs/An%20Introduction%20to%20FINOS.pdf) (if necessary)
 - [FINOS Maintainers cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet/)
 - [FINOS Project/Standards Governance](https://community.finos.org/docs/governance)
 - [FINOS Project Lifecycle](https://community.finos.org/docs/governance/Software-Projects/project-lifecycle)

## Record The Contribution (FINOS Infra)
- [x] (optional) Identify and Assign FINOS Strategic Advisor - @maoo 

# 2. Approval

The [FINOS Technical Oversight Committee](https://github.com/finos/technical-oversight-committee) (TOC) is responsible for approving FINOS project contributions; feel free to check their [contribution principles](https://github.com/finos/technical-steering-committee/blob/master/contribution-principles.md).

If needed, the TOC will request a follow up either via GitHub Issue comments or by inviting project leads to one of their recurrent meetings.

Tasks (for FINOS Infra/TOC)
- [x] Prioritise this issue on the [TOC Backlog](https://github.com/orgs/finos/projects/39)
- [x] Assign this issue to @colineberhardt
- [x] Add the `ready-for-toc` label
- [x] TSC to invite contributors to present their project
- [x] FINOS TOC approves/rejects the contribution

## TOC Findings / Report
*TOC to enter findings summary here.*

# 3. Preparing For Onboarding

Before the FINOS team can onboard your project, there are a few housekeeping that need to be taken care of.  These must be completed by the contributor, with help if required from the FINOS Infra.   

## Kick-off meeting
- [x] Set up kick-off meeting with project leads
- [x] Run kick-off meeting
  - [x] Walk through the checklist in part 1, ensure all the questions are answered and remove items that don't apply

## Logo / Trademarks
 - [x] Request logo design from `help@finos.org`
 - [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws. _(Infra team to validate with FINOS Legal team if anything important is raised)_

## FINOS Project Blueprint
- [x] [finos-admin](http://github.com/finos-admin) is Admin of the GitHub repository to transfer
- [x] Apply project blueprint contents - see [ODP docs](https://community.finos.org/docs/collaboration-infrastructure#finos-project-blueprint)
    - [x] README.md file contains the sections in the [README Template](https://github.com/finos/software-project-blueprint/blob/main/README.template.md)
    - [x] Project FINOS badge in README (incubating)
    - [x] [OpenSSF Passing Badge](https://bestpractices.coreinfrastructure.org/en) (optional)
    - [x] License in README
    - [x] Contributing in README
    - [x] `CONTRIBUTING.md`
    - [x] `LICENSE` (replace `{}` placeholders)
    - [x] Ensure that the proper project governance is in the CONTRIBUTING.md file
- [x] [All incubating criteria](https://community.finos.org/docs/governance/Software-Projects/stages/incubating) are checked and documented below

_Add documentation here_

# 4.  FINOS Onboarding

This is performed by FINOS Infra once the three previous stages are complete, with support from the contributor and the FINOS Infra team.

## Maintainers, Contributors and CLAs 
- [x] Identify other existing contributors (assuming there's a contribution history (eg Git history)
- [x] Check if maintainers and other contributors are all covered by FINOS CLA
- [x] Reach out to contributors and employers to coordinate CLA signatures
- [x] Invite GitHub usernames to GitHub FINOS Org
- [x] Create `<project-name>-maintainers` GitHub team and invite users

## Validation (only if code is contributed)
- [x] Backup (even with screenshot) GitHub permissions of the repository to transfer
- [x] Check GitHub repository transfer requirements:
  - [x] [finos-admin](http://github.com/finos-admin) has `Admin` to all repositories to transfer
  - [x] [finos-admin](http://github.com/finos-admin) ia allowed to transfer repositories out of the org
  - [x] if the repository is owned by a user (and not an org), the user must be able to transfer the repository to [finos-admin](http://github.com/finos-admin)
- [x] The codebase doesn’t have HIGH or CRITICAL CVEs across direct and transitive libraries - https://github.com/finos-labs/traderX/pull/30
- [x] The codebase doesn’t have any unfriendly licenses across direct and transitive libraries
- [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws (to be validated with FINOS Legal team)
- [x] [All incubating criteria](https://community.finos.org/docs/governance/Software-Projects/stages/incubating) are met (review documentation provided above)

## Code transfer 
- [x] Transfer all code assets as GitHub repositories under github.com/finos
- [x] Rename main branch to `main` (instead of `master`)
- [x] Configure `finos-admins` (`Maintain` role) and `finos-staff` (`Triage` role) team permissions

## Project Communication Channel(s)
- [x] Link communication channels linked front-and-center in the project README.md

## Repository setup 
- [x] Enable EasyCLA
- [x] Add project to metadata
- [x] Add identities, orgs and affiliations to metadata (deprecated by EasyCLA)
- [x] Add logo to FINOS landscape
    - [x] Create `staging` branch on `finos/finos-landscape`
    - [x] Merge `finos/metadata` changes on master (will udpdate `landscape.yml` in `finos/finos-landscape`)
    - [x] Create PR from `staging` branch on `finos/finos-landscape`
    - [x] Review Netlify preview
    - [x] Merge PR
- [x] Add project maintainers emails to [finos-project-maintainers@finos.org](https://groups.google.com/a/finos.org/g/finos-project-maintainers/members) list
- [x] Add project maintainers GitHub usernames to the [project-maintainers Team](https://github.com/orgs/finos/teams/project-maintainers/members)
- [x] Ask @jgavronsky to mark contribution as "Active" within LF systems
- [x] (best effort) Update release coordinates and code namespace to include `finos`
- [x] Check that CVE (and preferably static code analysis, if applicable) scanning is in place
- [x] Enable automated dependency update, using [Renovate](https://renovatebot.com/)
- [x] Enable [branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) (`Require a pull request before merging`)

# 5. Announcement 

(Lead: Project Lead and FINOS Infra team)

- [x] Update the contribution status to "Active" by sending another email to **LF Legal Representative** with the name of the project and its new status.
- [x] Lead maintainer works with FINOS marketing to send out announcement to announce@finos.org , checkout announcement template at the [Contribution page](https://community.finos.org/docs/governance/Software-Projects/contribution#step-5-contribution-announcements)
- [x] Notify FINOS marketing (@grizzwolf + finos-marketing internal Slack channel)

**Comment by brunodom** [comment]
On behalf of the TOC and after evaluating this contribution against our approval [principles](https://github.com/finos/technical-oversight-committee/blob/master/contribution-principles.md) [(as outlined in this e-mail thread](https://lists.finos.org/g/toc/message/233)). I am glad to approve the contribution!

**Comment by TheJuanAndOnly99** [comment]
Congratulations @DovOps @ctiltman, and thanks for contributing TraderX to FINOS!

Contribution announcement can be found at https://groups.google.com/a/finos.org/g/announce/c/19pa7DJzGfE
