### ISSUE TITLE
Feedback Needed : FINOS Community 2020 KPIs

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#28]
### Description
During the FINOS Pan PMC meeting on 18th February 2020, @mcleo-d introduced the PMC community to the draft FINOS community 2020 KPIs.

* Quarterly advocacy blog post, webinar, training session on opportunities for OSS in FSI
* Quarterly project specific blog post / event / etc.
* Refer upstream and downstream projects for inclusion in FINOS
* Execute CCLA/ICLA
* Provide howtos, samples, tutorials
* Incubating projects execute on FINOS recommendations in a timely manner
* Maintain a public task list and list of "good first issues"
* Projects always “build” 
* Consistently produce releases, SDKs, reference implementations and samples

### Feedback Required
It would be great to get your feedback on the FINOS Community 2020 KPIs below, especially if you have ideas about how the FINOS community can help the foundation fulfil these goals.  

<img width="453" alt="Screenshot 2020-02-21 at 12 45 44" src="https://user-images.githubusercontent.com/6029572/75035780-2ded8080-54a8-11ea-86a5-ac44663471cf.png">

**Comment by mindthegab** [comment]
We'll do this in 2021 working with @finos/project-maintainers.
