### ISSUE TITLE
Question : Identifying Industry Wide Business Challenges

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#29]
### Description

FINOS has recently started a collaboration group within FDX that's focused on solving common DevOps problems in finance and how FINOS can overcome as a foundation.

This DevOps idea was generated from within the FINOS community.

### Question to Answer

How can we **Identify**, **Prioritize** and **Focus** ourselves on industry wide business challenges that affect areas of FINOS that are engineering and non-engineering focused?

**Comment by maoo** [comment]
Given that this issue is open since more than 2 years and refers to FINOS Programs which don't exist anymore (FDX), I think it's safe to close it.
