### ISSUE TITLE
Adopt morganstanley/fdc3-dotnet as the .NET API signatures for FDC3

### ISSUE THREAD

**Issue by kriswest** [finos/community#297]
## Business Problem
The FDC3 documentation has long included the statement that:

FDC3 is platform- and programming language-independent.

https://fdc3.finos.org/docs/supported-platforms

However, it currently only defines a set of language bindings for TypeScript/JavaScript, although there exist a number of proprietary bindings for the FDC3 Desktop Agent API in other languages, particularly .NET and Java. There exists an open issue in the FDC3 project to improve on this state by adopting standard bindings for other languages:

https://github.com/finos/FDC3/issues/990
 
## Proposed Solution
The FDC3 maintainers seek to adopt a set of bindings for FDC3 .NET, which have been proposed as a contribution to FINOS by @bingenito @ Morgan Stanley: https://github.com/finos/FDC3/issues/931

We desire to migrate these bindings to a FINOS-hosted repository under the same governance as the existing FDC3 repository and to appoint additional maintainers to help keep it up-to-date with changes to the FDC3 Standard. The use of a separate repository will simplify maintenance and setup of publishing tasks necessary to make the bindings available via nuget, whilst using the same governance/maintainers team will ensure that the .NET binding remain in-sync with the FDC3 Standard.

We anticipate adopting further bindings for other languages in due course, and expect to follow the same model established for the .NET bindings.

## Tentative Roadmap
The process that we propose for adoption of these bindings is to:

- Seek the approval of FINOS and the TSC to migrate the Morgan Stanley repository to a FINOS hosted repository (e.g. finos/fdc3-dotnet)
- Seek initial approval of the FDC3 Standards Working group (and solicit review by participants) at the next meeting (Thurs 30th Nov 2023)
- Update the namespace used in the project from `MorganStanley.Fdc3` to `FINOS.Fdc3` and apply any reasonable changes proposed during review and agreed by participants.
- Raise a PR to include the standardized .NET signatures in the FDC3 documentation site
- Hold a vote on the adoption of the Standardized .NET signatures by the FDC3 community (via the fdc3-participants list) and subsequently merge the PR to include them in the documentation.
 
## Current State
We believe that the current state of the of the project proposed for adoption provides a complete set of FDC3 API bindings and Context object definitions for FDC3 2.0 and is currently being updated to include types added in FDC3 2.1 (the current release of FDC3).

Work has begun on adding the bindings to the FDC3 documentation site under draft PR https://github.com/finos/FDC3/pull/1108 [preview](https://deploy-preview-1108--fdc3.netlify.app/docs/next/api/ref/DesktopAgent). It is expected that providing a draft of the updated documentation will simplify review of the bindings by the FDC3 community prior to voting on the inclusion.
 
## Existing Materials

 - [x] GitHub
   - [x] URL for the repository: _<https://github.com/morganstanley/fdc3-dotnet>_
   - [x] Project Name: _fdc3-dotnet_
   - [x] _Repository is public_
 - [x] Was the project ever released? _(yes)_ 
   - [x] If so, are releases public? _(yes, see <https://www.nuget.org/packages/MorganStanley.Fdc3>)_ 
   - [x] And what's the latest released version? _2.0.0-alpha.7_
 - [x] Existing Project Documentation _(The FDC3 Standard docs for the API and Context types are replicated as XML docs within the project, while the FDC3 website will provide the main documentation as it does for the TypeScript bindings)_
 - [x] Is there a logo? _(yes / no)_
 - [x] Are meetings currently held for the project? _(These will be handled via the existing FDC3 project meetings)_
 - [x] Are meeting minutes, agenda and attendance tracked? _(These will be handled via the existing FDC3 project meetings)_

### Maintainers
Existing FDC3 project maintainers and editor will be applied to the project when adopted, with the maintainers team expanded to include @bingenito 

### Confirmed contributors
|Name                        |Affiliation              |Work Email Address             |Github / GitLab username              |
|----------------------------|-------------------------|-------------------------------|--------------------------------------|
|Brian Ingenito        |Morgan Stanley              |brian.ingenito@morganstanley.com             |@bingenito                     |

### Target Contributors
Developers from any firm making use of the .NET bindings for the FDC3 API

## Project Communication Channel(s)

- [x] Contributor to ask maintainers which communications channels they'd like to use:
- Asynchronous
  - [x] GitHub Issues _(public)_
  - [x] Mailing-list (Existing FDC3 mailing lists)
  - [x] FINOS Slack Channel (consisting of the above described contributors)
    - [x] General (public) _(Exisitng #fdc3 channel)_ 
    - [X] Leadership (private) _(Existing #fdc3-maintainers channel)_
- Synchronous
  - [x] Recurring meetings (Existing FDC3 meetings)

## Understanding FINOS Onboarding Requirements

As a project onboarding into FINOS, you will need to familiarize yourself and your contributor team with the following materials:

 - [FINOS overview](https://www.finos.org/hubfs/An%20Introduction%20to%20FINOS.pdf) (if necessary)
 - [FINOS Maintainers cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet/)
 - [FINOS Project/Standards Governance](https://community.finos.org/docs/governance)
 - [FINOS Project Lifecycle](https://community.finos.org/docs/governance/Software-Projects/project-lifecycle)

# 3. Preparing For Onboarding

Before the FINOS team can onboard your project, there are a few housekeeping that need to be taken care of.  These must be completed by the contributor, with help if required from the FINOS Infra.

## Logo / Trademarks
 - [x] Request logo design from `help@finos.org` _(if needed)_
 - [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws. _(Infra team to validate with FINOS Legal team if anything important is raised)_

## FINOS Project Blueprint
- [x] [finos-admin](http://github.com/finos-admin) is Admin of the GitHub repository to transfer
- [x] Apply project blueprint contents - see [ODP docs](https://community.finos.org/docs/collaboration-infrastructure#finos-project-blueprint)
    - [x] README.md file contains the sections in the [README Template](https://github.com/finos/software-project-blueprint/blob/main/README.template.md)
    - [x] Project FINOS badge in README (incubating)
    - [ ] [OpenSSF Passing Badge](https://bestpractices.coreinfrastructure.org/en) (optional)
    - [x] License in README
    - [x] Contributing in README
    - [x] `CONTRIBUTING.md`
    - [x] `LICENSE` (replace `{}` placeholders)
    - [x] Ensure that the proper project governance is in the CONTRIBUTING.md file
- [x] [All incubating criteria](https://community.finos.org/docs/governance/Software-Projects/stages/incubating) are checked and documented below

_Add documentation here_

# 4.  FINOS Onboarding

This is performed by FINOS Infra once the three previous stages are complete, with support from the contributor and the FINOS Infra team.

## Maintainers, Contributors and CLAs 
- [x] Identify other existing contributors (assuming there's a contribution history (eg Git history)
- [x] Check if maintainers and other contributors are all covered by FINOS CLA
- [x] Engage with FINOS Legal team to figure out what’s needed to cover all maintainers and contributors with FINOS CLA
- [x] Reach out to contributors and employers to coordinate CLA signatures
- [x] Invite GitHub usernames to GitHub FINOS Org
- [x] Create `<project-name>-maintainers` GitHub team and invite users

## Validation (only if code is contributed)
- [x] Backup (even with screenshot) GitHub permissions of the repository to transfer
- [x] Check GitHub repository transfer requirements:
  - [x] [finos-admin](http://github.com/finos-admin) has `Admin` to all repositories to transfer
  - [x] [finos-admin](http://github.com/finos-admin) ia allowed to transfer repositories out of the org
  - [x] if the repository is owned by a user (and not an org), the user must be able to transfer the repository to [finos-admin](http://github.com/finos-admin)
- [x] The codebase doesn’t have HIGH or CRITICAL CVEs across direct and transitive libraries
- [x] The codebase doesn’t have any unfriendly licenses across direct and transitive libraries
- [x] (optional - if a build system is provided) The build process runs successfully
- [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws (to be validated with FINOS Legal team)
- [x] [All incubating criteria](https://community.finos.org/docs/governance/Software-Projects/stages/incubating) are met (review documentation provided above)

## Code transfer 
- [x] Transfer all code assets as GitHub repositories under github.com/finos
- [x] Rename main branch to `main` (instead of `master`)
- [x] Configure `finos-admins` (`Maintain` role) and `finos-staff` (`Triage` role) team permissions

## Project Communication Channel(s)
- [x] Create the identified communication channels during infra set up
- [x] Link communication channels linked front-and-center in the project README.md

## Repository setup 
- [x] Enable EasyCLA
- [x] Add project to metadata
- [x] Add project maintainers emails to [finos-project-maintainers@finos.org](https://groups.google.com/a/finos.org/g/finos-project-maintainers/members) list
- [x] Add project maintainers GitHub usernames to the [project-maintainers Team](https://github.com/orgs/finos/teams/project-maintainers/members)
- [ ] (best effort) Update release coordinates and code namespace to include `finos`
- [x] Check that CVE (and preferably static code analysis, if applicable) scanning is in place
- [x] Enable automated dependency update, using [Renovate](https://renovatebot.com/) (They are using dependabot)
- [x] Enable [branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) (`Require a pull request before merging`)

# 5. Announcement 

(Lead: Project Lead and FINOS Infra team)

- [ ] Update the contribution status to "Active" by sending another email to **LF Legal Representative** with the name of the project and its new status.
- [ ] Lead maintainer works with FINOS marketing to send out announcement to announce@finos.org , checkout announcement template at the [Contribution page](https://community.finos.org/docs/governance/Software-Projects/contribution#step-5-contribution-announcements)
- [ ] Notify FINOS marketing (@grizzwolf + finos-marketing internal Slack channel)

**Comment by bingenito** [comment]
This looks good as discussed @kriswest.  I'd add @psmulovics  as a maintainer although that can be done outside of this transfer.  I have approvals on my side.  Once we can go ahead I'd rather do the readme/contribution updates after transfer.  The repo can be private until that is done.

**Comment by maoo** [comment]
Thanks @bingenito and @kriswest for this contribution!

We will start looking into it and keep you posted, hopefully before the end of next week.

**Comment by maoo** [comment]
All clear, thanks @kriswest and @bingenito. We'll start working on it and update the issue with the progress.

**Comment by TheJuanAndOnly99** [comment]
Code transfer is complete. Still working on potential updates to release namespace and announcement.

**Comment by maoo** [comment]
@kriswest - can this issue be closed, or there's still something left? Was this contribution announced somewhere?

**Comment by kriswest** [comment]
I believe we're still waiting to merge the adoption PR as there's some awkward content (supported platforms page) to write. However, thats covered on an FDC3 issue and PR - the community provided consent to adopt, which was documented in Standards Working Group meeting minutes - hence upto you if thats sufficient to close the community issue.


[signature_839383943]<https://interop.io/>

Kris West

[signature_4282944278]<https://www.linkedin.com/in/kriswest/>

Director, Consulting Services

p +44 7715104292│e ***@***.******@***.***>

Finsemble and Glue42 are now interop.io<https://interop.io/welcome-to-interop-io/>



________________________________

**Comment by maoo** [comment]
Thanks @kriswest ! After checking with @bingenito and @robmoffat I think we're all confident that the contribution process is complete and therefore this issue can be closed. Thanks for your contribution Brian!
