### ISSUE TITLE
Maintainers Wanted! FINOS Engineering Huddle at NatWest Group, London - Wed 27th March from 5:30pm GMT

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#308]
Hello 👋🏻 

I’m inviting FINOS Maintainers to join an open source engineering huddle at NatWest Group, London to present their FINOS projects and standards on Wed 27th March from 5:30pm GMT 🌈💻🌍

Get in contact through the comments to add your FINOS project / standard to the lightning talk agenda 🤜🏻⚡️

Let’s present our open source in finance projects to the engineers who need them! 🛠️

**Comment by maoo** [comment]
Thanks for this @mcleo-d - closing this, but feel free to reopen if there are tasks missing.
