### ISSUE TITLE
Extrapolate FDC3 demos from Plexus program (docs repo)

### ISSUE THREAD

**Issue by maoo** [finos/community#40]
- [ ] Are they compatible with FDC3 1.1 ?
- [ ] Are they maintained ?
- [ ] Is there value in these demos?

**Comment by mcleo-d** [comment]
Thanks for updating this story @maoo. I'll get onto the Plexus team to investigate. 👍

**Comment by mcleo-d** [comment]
Paul Whitby emailed, with @mindthegab's input, on Thursday 9th July 2020.

Paul to reach out to Leslie Spiro as contributor of the code.

**Comment by mcleo-d** [comment]
FDC3 demos raised in Plexus Interop API meeting on 17th July 2020 below.

https://finosfoundation.atlassian.net/wiki/spaces/PLX/pages/1813643265/2020-07-17+Interop+API+WG

* Leslie Spiro to add Plexus Interop API inclusion into FDC3 onto the FDC3 agenda
* Leslie Spiro to raise a Plexus Interop API pull request against the FDC3 project
* Leslie Spiro to assess whether to contribute the Plexus Interop API demos to FDC3, or Archive, based on the FDC3 inclusion decision.

**Comment by mcleo-d** [comment]
@mcleo-d awaiting feedback from https://github.com/finos/FDC3/issues/230 on the request raised by Leslie Spiro.

**Comment by mcleo-d** [comment]
The following issues have been raised by Leslie Spiro, against the FDC3 project, but are still to be agreed / resolved by the FDC3 team.

- https://github.com/finos/FDC3/issues/203
- https://github.com/finos/FDC3/issues/231#issuecomment-666636683

**Comment by mcleo-d** [comment]
Emails sent to Leslie Spiro as positive comments made on FDC3 issues that might have been missed in the notifications.

**Comment by mindthegab** [comment]
Blocked on https://github.com/finos-plexus/finos-plexus.github.io/issues/48.

**Comment by mcleo-d** [comment]
The following email was sent to Leslie Spiro requesting a response.

---

Hi Leslie,

Just to inform you the following issue has been raised on the Plexus API project and needs a response.

https://github.com/finos-plexus/finos-plexus.github.io/issues/48#issue-696014925

Are you okay to respond via GitHub?

Kind regards,

James.

**Comment by mcleo-d** [comment]
Hi @mindthegab,

Please find an update from Plexus Desktop API project meeting on 18th September 2020 regarding the contribution of the API and Demos to the FDC3 project.

https://finosfoundation.atlassian.net/wiki/spaces/PLX/pages/1967915009/2020-09-18+Interop+API+WG

- Leslie Spiro raising API and Demo contributions with the FDC3 team on Thursday 24th September
  - If the FDC3 team do not accept the Demos or API contributions.
    - The Demos will be archived in the current FINOS-Plexus organisation on GitHub.
      - https://github.com/finos-plexus/finos-plexus.github.io/tree/master/demos
    - The Plexus Desktop API will be contributed to the Plexus Interop team to be absorbed into the project.
    - The Plexus Desktop API project will be wound down.

**Comment by mcleo-d** [comment]
The following actions have taken place by @mcleo-d and @maoo to close this issue as documented in https://github.com/finos-plexus/plexus-fdc3-samples/issues/48

- Repo name changed from **finos-plexus.github.io** to **plexus-fdc3-samples**.
- Pull request #19 scope changed from adding an `INCUBATING` badge to `ARCHIVED` and assigned to @maoo for review and merge.

- Repo name changed from **finos-plexus.github.io** to **plexus-fdc3-samples**.
- Pull request #19 scope changed from adding an `INCUBATING` badge to `ARCHIVED` and assigned to @maoo for review and merge.

**Comment by maoo** [comment]
all done! pr merged and repo archived
