### ISSUE TITLE
How should we call the strategic initiative to promote Open Source in regulatory compliance specification and implementations?

### ISSUE THREAD

**Issue by mindthegab** [finos/community#47]
Over the last year our Community identified regulatory implementation, interpretation and even specification as areas of opportunity for open source collaboration, given they usually are shared, non differentiating requirements, where there's a huge opportunity for mutualization/cost sharing/saving.

To date we have hosted an introductory webinar with 30+ regulators, launched [an initial landing page](https://www.finos.org/en/open-source-finreg) and working on multiple project opportunities. 

But as FINOS team, lead by @aitana16 and @toshaellison, we have been struggling on how to name this initiative and message around it. 

So we'd like to ask the input of the Community in helping us with this dilemma. I'll list below a couple of options we came up with, so please post a comment below with your choice or if you have alternative suggestions:

1. Open Source FinReg (currently what's used in our [landing page](https://www.finos.org/en/open-source-finreg)

2. Open RegTech 

3. Open Source RegTech

We'd love to hear from you, thanks in advance for taking the time!

/cc @finos/finos-staff

**Comment by mcleo-d** [comment]
Great question @mindthegab. I have a couple of ideas but look forward to the community suggestions before I make mine known 👍

**Comment by maoo** [comment]
I vote #2 (2 words)

**Comment by pbouda** [comment]
How about "RegTech Open Source" in parallel to "FinTech Open Source"? So "REGOS". From the proposals I think option 2 is the best.

**Comment by aitana16** [comment]
I vote for #1 =)

**Comment by toshaellison** [comment]
I vote #1

**Comment by alstratigos** [comment]
+1 for #1
<https://www.finos.org/>Alexandra Stratigos | Chief of Staff
FINOS
📱 +1 (650) 996-9820 <+1-650-996-9820>

<https://finos.github.io/>  <https://twitter.com/finosfoundation>
<https://www.facebook.com/finosfoundation>

<https://linkedin.com/company/finosfoundation>

**Comment by mcleo-d** [comment]
I vote **Open RegTech** - Number 2

**Comment by ColinEberhardt** [comment]
I prefer options 2 & 3 - I think it makes sense to use an existing and widely used term (RegTech), rather than creating a new one (FinReg).

**Comment by mindthegab** [comment]
Thanks everyone for chiming in here!

It sounds like the consensus of the Community is towards "Open RegTech" or "Open Source RegTech".

We will provide this recommendation to the "Reg" Special Interest Group whose creation is being discussed [in this issue](https://github.com/finos/community/issues/66) and who's going to be the main forum where we convene interest and make progress on this initiative.  

Please feel free to chime in directly on that issue and we'd love for you to join / participate if you are interested!

I really appreciate everyone's input here.

**Comment by mikejstevenson** [comment]
I entirely agree with favoring RegTech over FinReg, for the reasons @ColinEberhardt sets out. I think I prefer 2 (Open RegTech) more, but I'm also comfortable with 3.

**Comment by toshaellison** [comment]
To provide more context, my reason for preferring FinReg over RegTech is that I feel RegTech, because it is widely used, has a strong connotation which does not fully encompass our aspirations. We want the implementation _and_ the interpretation _and_ even the construction of the regulations themselves to leverage open source. As Gab writes, however, this is a good topic for the SIG (and I'll go with majority).

**Comment by DavidVtFreshAIR** [comment]
@toshaellison I also vote for #2, the term finreg doesnt really exist, and the effort to create the regulations themselves is more comprehensively covered by name "Digital Regulatory Reporting" or DRR, efforts which are already underway with implications for the need of open source, data standards, and building regulatory confidence with new solutions.
