### ISSUE TITLE
Create GitHub discussion (or mailing-list) containing all and only FINOS Project Leads

### ISSUE THREAD

**Issue by maoo** [finos/community#50]
In order to foster direct communication across FINOS Project Leads, it would be useful to have a channel to vehicle discussions.

Requirements are:
1. All project leads should be able to post a message, without any moderation
2. All contents should be publicly available
3. Everyone should be able to post a message; project leads should be able to moderate the content before being posted

Right now, ODP provides the following options
1. GitHub (Repository) Discussion - Tested all requirements except 3.
2. GitHub (Team) Discussion - Requirement 2 doesn't match
3. Google Group @finos.org - All requirements match, but depending on firewall restrictions, 3 may not match for some project leads

Feedback is welcome.

**Comment by maoo** [comment]
For now, we'll create a mailing-list, manually managed and define a SOP related with project onboarding

In the future we will discuss if/when introducing a GitHub discussions.

**Comment by mindthegab** [comment]
I propose for now:

- Go with a google group

But also create a Github Group with all Project Leads, so we can tag them in issues. Let's punt on discussions for now until we make a decision on email systems and chats.

**Comment by mindthegab** [comment]
I have created https://groups.google.com/a/finos.org/g/finos-project-maintainers/ and added all current project lead maintainers (terminology from the new governance, see #45) /cc @brooklynrob @aitana16 @mcleo-d 

I have also added that to the community@ alias. 

What's left to do @maoo is:

- [ ] Create a github group will all project maintainers
- [ ] Agree with @aitana16 @mcleo-d @brooklynrob @toshaellison how, when a project lead is updated, not only metadata is updated but also the google group and the github group

**Comment by maoo** [comment]
GitHub Team created! See https://github.com/orgs/finos/teams/project-maintainers/members . It's composed by 23 members , while 8 invitations are pending, as the users haven't accepted yet the invitation to the FINOS org.

@mcleo-d - could you help us reaching out to the users with a pending invitation and confirm that 1) they're still affiliated with the org we have on file 2) they're still leading the FINOS project?

@aitana16 - can we discuss this item during our call on Monday, so we can review SOP docs and update them? TY!

**Comment by aitana16** [comment]
Sounds good @maoo I've added it to the agenda

**Comment by brooklynrob** [comment]
See my [comment](https://github.com/finos/open-developer-platform/issues/151#issuecomment-657662971) on [ODP Issues 151](https://github.com/finos/open-developer-platform/issues/151)

FINOS provides a lot of tools, policy/governance, and infrastructure for our projects which, I hope, everyone thinks is a very good thing and a key part of our value proposition to our members, the wider FINOS community of project contributors and consumers, and our wider industry. 

With this context, the surface area of everything a project committer/maintainer, and esp. a project lead, needs to know in terms of tools, processes, and infrastructure re FINOS is quite large. Further there is a lot that had been added (e.g., the new ODP Github issues meeting formats), changed (program deprecation), leveraged from the LF (e.g., the new landscape at landscape.finos.org and built from https://github.com/finos/finos-landscape/), etc. 

I would suggest we consider:
- Some form of formal project maintainer/project lead on-boarding training program, perhaps codified as a free course on LF WebEx infrastructure that could even be a pre-req for being elected to be a maintainer by a project. 
- Some recurring knowledge sharing and Q&A (perhaps a "brown bag lunch") to further/better communicate what's available and being revised/added for project leads (a bit akin to what was once done in pan-PMC meetings)

**Comment by maoo** [comment]
All done here, see https://docs.google.com/document/d/1A3i88DcsGrMF26RfCO5aS6UIC9g6pmYzZYE2XGcm3JA (specifically the infra setup section). Closing.
