### ISSUE TITLE
Planning Q3 All Community call

### ISSUE THREAD

**Issue by mindthegab** [finos/community#53]
This issue is a place holder to build the agenda for the next quarterly community call, planned for the 2nd half of August.

Current proposed topics would be:

- [x] Progress update on [Q3 focus projects](https://github.com/finos/community/tree/master/focus-projects#current-focus-projects)
- [x] Walkthrough of new governance per #45
- [x] Asks for project leads re security vulnerabilities
- [x] Share community KPIs

/cc @mcleo_d

**Comment by brooklynrob** [comment]
See my comment at https://github.com/finos/community/issues/50#issuecomment-657699295 -- I think using this call to highlight some key tools and processes that leads and maintainers should be aware and using - existing, new, and recently revised - would be a good idea, especially given all that is new and revised.

**Comment by mcleo-d** [comment]
Thanks for raising @mindthegab. I have moved to **Prioritised** on the team kanban 👍

**Comment by mcleo-d** [comment]
The DevOps Mutualization group have been engaged to present here https://github.com/finos/community/issues/52#issuecomment-671421613

**Comment by mcleo-d** [comment]
The DataHub / DataHelix projects have been engaged to present here https://github.com/finos/datahub/issues/40

**Comment by mindthegab** [comment]
Here's the skeleton deck @mcleo-d https://docs.google.com/presentation/d/1dpi92VgCevCDTa_2RtB0grC64qTvIQRSY8qh-EfVrok/edit#slide=id.g864866eb9c_0_0

**Comment by mindthegab** [comment]
> See my comment at [#50 (comment)](https://github.com/finos/community/issues/50#issuecomment-657699295) -- I think using this call to highlight some key tools and processes that leads and maintainers should be aware and using - existing, new, and recently revised - would be a good idea, especially given all that is new and revised.

You got it mate @brooklynrob https://docs.google.com/presentation/d/1dpi92VgCevCDTa_2RtB0grC64qTvIQRSY8qh-EfVrok/edit#slide=id.g94364f9c55_1_591

**Comment by mindthegab** [comment]
Thanks for all your input @mcleo-d @brooklynrob @toshaellison @aitana16 @alstratigos and everyone.

Attached the final version we'll go through tomorrow. Closing this one.

[2020Q3 - All Community Call .pdf](https://github.com/finos/community/files/5199878/2020Q3.-.All.Community.Call.pdf)
