### ISSUE TITLE
Rename (or remove) pmcs.finos.org

### ISSUE THREAD

**Issue by maoo** [finos/community#54]
This repo builds the pages served on pmcs.finos.org , which is a confusing term, now that PMCs have been all disbanded.

I expect that some changes to the `docs` and `website` contents will be needed as well, to accommodate PMC disband and (maybe?) publish new Governance contents.

Finally, we should move from Travis CI to GitHub Actions, reusing the Docusaurus build Action we're using across all other repositories.

Assigning to @mindthegab for review and prioritization.

**Comment by maoo** [comment]
Remove pmcs.finos.org , no other change required.

**Comment by maoo** [comment]
All done here! @toshaellison @grizzwolf @mcleo-d @brooklynrob @aitana16 - do you know any place across our website, wiki  or github docs where the link pmcs.finos.org is linked to? We'd need to update them to github.com/finos/community

**Comment by mcleo-d** [comment]
Assigned to @mindthegab by @maoo during the FINOS Tech Leadership Meeting.
