### ISSUE TITLE
Work with software projects to adopt new project governance

### ISSUE THREAD

**Issue by mindthegab** [finos/community#58]
In #45 we've introduced a synthetic and simplified governance that fits in a CONTRIBUTING.md file.

Now that with #51 the governance was adopted we need to consider raising pull requests to projects to adopt this governance in their projects.

We'll outline progress here:

- [ ] Identify projects to submit PRs to
- [ ] Work with key projects to make sure they are prioritized

**Comment by mindthegab** [comment]
This is blocked on https://github.com/finos/project-blueprint/issues/17 /cc @maoo @copiesofcopies

**Comment by maoo** [comment]
All done, closing issue.
