### ISSUE TITLE
Creation of a FINOS project to continue CDM Extension work after the Alloy Pilot

### ISSUE THREAD

**Issue by mindthegab** [finos/community#64]
Per https://github.com/finos/finos-fo/issues/38: 

- **CDM work**: let’s explore the creation of a formal FINOS project to continue developing extensions to the CDM with Alloy (such as the FX Option revisions done during the pilot). The CDM itself (https://gitlab.alloy.finos.org/alloy-pilot/cdm) has been imported into the hosted instance of Alloy and is available to be used for further modeling effort(s) within FINOS. **Next steps** would be to identify interest and maintainers for such a project and make sure ISDA is on board to avoid any forking. Chime in on this #issue to continue on this topic. 

@brooklynrob assigning to you as I know you and @aitana16  are going to take the lead here to get this sorted by the time Alloy becomes fully open source.

_Originally posted by @mindthegab in https://github.com/finos/finos-fo/issues/38#issuecomment-678567436_

**Comment by lolabeis** [comment]
@mindthegab @brooklynrob @aitana16 I would have thought that IF there is indeed interest to continue developing extensions to the CDM under FINOS, this would provide the requisite use-case(s) and scope of activity for the "Financial Object" project (as per https://github.com/finos/finos-fo/issues/38), as opposed to keeping it under the Alloy project?

Under this paradigm:
1. The FO project focuses on modelling, including the CDM, using tool made available to the FINOS Community (such as Alloy) to facilitate the workings of that forum.
2. The Alloy project focuses on further development of the Alloy platform itself, with a possible focus on the inter-operability question which was raised in #38.

**Comment by mindthegab** [comment]
> @mindthegab @brooklynrob @aitana16 I would have thought that IF there is indeed interest to continue developing extensions to the CDM under FINOS, this would provide the requisite use-case(s) and scope of activity for the "Financial Object" project (as per [finos/finos-fo#38](https://github.com/finos/finos-fo/issues/38)), as opposed to keeping it under the Alloy project?

I think there's general consensus Alloy (the platform) should progress as its own project(s), so that's how it will move forward.

The question is whether CDM related work should also be a separate project or just being folded under FO. I think given the history of FO, it might make sense to start fresh with a more defined scope around CDM extensions, which also gives the opportunity to identify new maintainers.  But, of course, ultimately up to the community to decide. 

And of course ISDA will have to play a key role in this decision, as our goal is to bring folks together for the benefit of the whole industry.

**Comment by lolabeis** [comment]
> I think there's general consensus Alloy (the platform) should progress as its own project(s), so that's how it will move forward.
> 
> The question is whether CDM related work should also be a separate project or just being folded under FO. I think given the history of FO, it might make sense to start fresh with a more defined scope around CDM extensions, which also gives the opportunity to identify new maintainers. But, of course, ultimately up to the community to decide.

@mindthegab Understand, and that makes sense. Whether it's under FO or a separate stream is subjective, and I don't know the whole history of the FO project, so defer to your better judgement.

Notwithstanding that positioning question, if contributions to the CDM are being made under such Finos project, we should concurrently discuss the positioning of the CDM's underlying Domain-Specific Language (the "Rosetta DSL") - which is currently under an Apache 2.0 license, but not under Finos. Maybe ultimately belongs to that same project?

And then having Alloy, Rosetta, etc, I would raise again the question about "platform inter-operability" for model development (a problem that the https://github.com/finos/morphir project is also looking at), so that indeed concerns between platform and model can be separated. We could look to address that issue as part of this new "CDM" project. We have some views which we can share - I'm sure the respective Alloy and Morphir teams also have some from their experience.

**Comment by mindthegab** [comment]
> Notwithstanding that positioning question, if contributions to the CDM are being made under such Finos project, we should concurrently discuss the positioning of the CDM's underlying Domain-Specific Language (the "Rosetta DSL") - which is currently under an Apache 2.0 license, but not under Finos. Maybe ultimately belongs to that same project?

Fully agreed. If the CDM was contributed under FINOS, we wouldn't need a "CDM Extensions" project, but we'd just have the "CDM" as a project in FINOS and extensions could be proposed via Pull Requests and optionally via Alloy as likely that makes it easier. The only reason we're floating the idea of an "extensions only" project is because there's not have been a decision yet on whether the CDM will land in FINOS.
 
> And then having Alloy, Rosetta, etc, I would raise again the question about "platform inter-operability" for model development (a problem that the https://github.com/finos/morphir project is also looking at), so that indeed concerns between platform and model can be separated. We could look to address that issue as part of this new "CDM" project. We have some views which we can share - I'm sure the respective Alloy and Morphir teams also have some from their experience.

Fully agreed and that's where I think having FINOS as a common umbrella could help bring these close to each other.

Bottomline, I think we are very much aligned here...
