### ISSUE TITLE
Proposal for the creation of a 'Regulation Innovation' Special Interest Group

### ISSUE THREAD

**Issue by DavidVtFreshAIR** [finos/community#66]
The Regulation Innovation SIG will be a community of people interested in creating open source solutions for regulatory and compliance issues. Creating open source solutions to regulatory compliance is particularly important because the market is currently using custom-built, one-off solutions, that are expensive, inefficient, and costly to manage and update over time. 

The proposed chair of the Regulation Innovation SIG will be Ian Hollowbread (ING) and initial sponsors will include AIR - the Alliance for Innovative Regulation, as well as representatives from 1-3 additional financial institutions.  This SIG will be of particular importance to banks because of the cost and implementation of compliance is very expensive.  The target audience will be compliance officers, and tech leaders responsible for compliance who are looking to create low-cost industry-wide scalable solutions.

**Comment by mindthegab** [comment]
For everyone interested in this potential group, which is now in the formation stage, please register your interest / comments / suggestions here. 

/cc @toshaellison @aitana16 probably worth linking this page on https://www.finos.org/en/open-source-finreg for increased visibility.

**Comment by h-grieve** [comment]
We're interested!

**Comment by pbouda** [comment]
We are interested, I am an NLP engineer at a RegTech startup. Interesting topics I think are open data, language corpora, language models, vocabularies, ontologies, data pipelines in regulation and compliance.

**Comment by mikejstevenson** [comment]
Please do include me in this too - many thanks

**Comment by mindthegab** [comment]
Great stuff - amazing to see initial interest, please keep it coming. On a related note, see input from the Community on the naming of this strategic initative - https://github.com/finos/community/issues/47#issuecomment-692863547. 

Might be one element for this SIG to decide upon, if and once created.

**Comment by srholt62** [comment]
Really interested in this initiative on behalf of JPMorgan.  Last year we worked with Tosha on some ideas for LATAM Payments reporting for regulators which showed just the tip of the iceberg in opportunities.

**Comment by johnmark** [comment]
I am very interested in participating in this initiative on behalf of CapOne. I've been in touch with David and am looking forward to initiating "regulation as code" initiatives and learning how to innovate in the field of compliance

**Comment by simonhull9** [comment]
Interested to be part of and contribute to this initiative.

**Comment by ianhollowbread** [comment]
Regulation matters, enabling safer and fairer markets is important to us all.  However the global complexities of embedding regulation across the ecosystem is no easy task.  Technologies and Innovation are presenting us new opportunities to rethink the way we achieve compliance.   

I am excited to work alongside industry experts and knowledge seekers to openly learn, share and progress under a everyday movement the way in which we manage regulation.

**Comment by DavidCowland** [comment]
definitely interested in this initiative

**Comment by mvanbuskirk** [comment]
We are very interested as well.

**Comment by waymarktechmark** [comment]
I am interested in this initiative on behalf of Waymark Tech

**Comment by nigelcobb** [comment]
I am interested in this idea on behalf of REGnosys

**Comment by kriscanonical** [comment]
I am interested to be part of this initiative. 
David and Gab, thanks for proposing this initiative. It is very relevant and timely as I believe most financial institutions have been witnessing an increase in their regulatory compliance cost year on year. I very much look forward to working alongside industry experts and peer group that is passionate about open innovation in finance sector.
Ian has so rightly expressed that innovation mindset and technology presents us an opportunity to promote open source in regulatory compliance specs & implementations across a complex ecosystem.

**Comment by aitana16** [comment]
### Thank you all for registering your interest in the Regulation Innovation Special Interest Group (SIG)!

We're excited to share that the FINOS Governing Board has approved the creation of the SIG, which will be led by Ian Hollowbread @ianhollowbread  and David Ehrich @DavidVtFreshAIR 

A [kick-off session](https://calendar.google.com/calendar/u/0/r/week/2020/11/10?eid=MDBwOG1nZGh1bDc4Ymc0MjB2ZnVxNTFmMDBfMjAyMDExMTBUMTcwMDAwWiBmaW5vcy5vcmdfZmFjOG1vMXJmYzZlaHNjZzBkODBmaThqaWdAZw&ctz=America/New_York&sf=true) is scheduled for **Tuesday November 10th at 12pm ET / 5pm UK**, please join us using the below details, and make sure to subscribe for updates by sending an email to open-regtech+subscribe@finos.org.

- **FINOS Regulation Innovation SIG: kick-off meeting**
    - Tuesday, November 10th at 12pm ET / 5pm GMT
    - Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
    - Meeting number: 127 988 1411
    - Password: d9kKJPdX5C9

We also look forward to seeing you at [OSSF](https://events.linuxfoundation.org/open-source-strategy-forum/) on November 12 and 13, which will feature a Regulation, Risk & Compliance Track with talks by AIR, the CFPB, Google and JP Morgan. Register [here](https://events.linuxfoundation.org/open-source-strategy-forum/register/).

**Comment by mindthegab** [comment]
Congratulations to everyone involved. On behalf of the Board I can confirm we're very excited about this group as we think there's major potential here. Kudos @DavidVtFreshAIR, Ian and everyone who participated in the formation of this group.

I'll close this issue as the group is approved - further activity will continue in this repo https://github.com/finos/open-regtech and meetings details are available above.
