### ISSUE TITLE
Symphony Java Toolkit - Project Contribution and Onboarding

### ISSUE THREAD

**Issue by maoo** [finos/community#67]
Please refer to https://finosfoundation.atlassian.net/browse/CONTRIB-74 for contribution description.

## Identify project meta
- [x] Project Title - `Symphony Java Toolkit - or symphony-java-toolkit - or SJT`
- [x] Category and sub-category (for FINOS Landscape) - `category: Symphony Ecosystem , subcategory: Applications`
- [x] Existing code or new Github repository - https://github.com/deutschebank/symphony-java-client-parent
- [x] Existing code releases (and which artifact repositories are used) - https://search.maven.org/search?q=com.github.deutschebank.symphony
- [x] Team composition: lead maintainer and other maintainers
- [x] Meetings (existing/yes/no) - `no`
- [x] Meeting minutes, agenda, attendance tracking (existing/yes/no) - `no`
- Continuous Integration (existing/yes/no) - `yes`
- Documentation website (existing/yes/no) - `no - using README.md`

## Maintainers, contributors and CLAs
- [x] For each maintainer identified in the previous step, collect: the following info:
  - Fullname
  - GitHub username
  - Corporate email address
- [x] Identify other existing contributors (assuming there's a contribution history (eg Git history)
- [x] Check if maintainers and other contributors are all covered by FINOS CLA
- [x] Engage with FINOS Legal team to figure out what’s needed to cover all maintainers and contributors with FINOS CLA
- [x] Reach out to contributors and employers to coordinate CLA signatures
- [x] Invite GitHub usernames to GitHub FINOS Org
- [x] Create `<project-name>-maintainers` GitHub team and invite users

## Code validation (only if code is contributed)
- [x] The codebase doesn’t have HIGH or CRITICAL CVEs across direct and transitive libraries
- [x] The codebase doesn’t have any unfriendly licenses across direct and transitive libraries
- [x] (optional - if a build system is provided) The build process runs successfully
- [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws (to be validated with FINOS Legal team)
- [x] The codebase complies with [FINOS Project Blueprint](https://odp.finos.org/docs/project-collaboration/#finos-project-blueprint)
- [x] [All incubating criteria](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530363/Incubating) are checked and documented below
- [x] Use new CONTRIBUTING doc - https://github.com/finos/community/blob/master/governance/Software-Projects/CONTRIBUTING.template.md (in the root folder)

## Voting
- [x] Assign issue to @mindthegab to trigger voting
- [x] FINOS accepts the contribution (and the contribution process can move forward)

## Code transfer and infra setup
- [x] (optional) Transfer code assets under github.com/finos
  - [x] [finos-admin](http://github.com/finos-admin) is Admin of the GitHub repository to transfer
  - [x] add plexus-user as outside collaborator of the repo
- [x] Add project to metadata
- Update Maven GroupId to have `org.finos` prefix - https://github.com/finos/symphony-java-toolkit/pull/80
- [x] Add identities, orgs and affiliations to metadata
- [x] Update project badge
- [x] Add logo to FINOS landscape
- [x] Add project maintainers emails to finos-project-maintainers@finos.org list
- [x] Add project maintainers GitHub usernames to the project-maintainers Team
- [x] Enable security vulnerabilities scanning - https://github.com/finos/symphony-java-toolkit/pull/81
- Enable meeting attendance tracking (optional)

## Announcement
- [x] Work with FINOS marketing to send out announcement to ~~community@finos.org~~ announce@finos.org , checkout announcement template on ~~https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/83034172/Contribute~~ https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/83034172/Contribute#Contribute-AnnounceEmailTemplate 

## Onboarding and training
- [x] FINOS Project Governance
- [x] FINOS Project Lifecycle
- [x] ODP Training

**Comment by mindthegab** [comment]
@maoo I checked a couple of boxes that I think were done - please double check and, in due time, complete the rest (no rush).

**Comment by maoo** [comment]
Contribution done, congratulations Rob and team!

Code is available here https://github.com/finos/symphony-java-toolkit
