### ISSUE TITLE
Plan ahead finoslabs + DCO (for AIR TechSprint)

### ISSUE THREAD

**Issue by mindthegab** [finos/community#68]
Per discussions on Monday, the following activities can start already:

- [x] creation of the finos-labs org
- [x] add FINOS branding to organisation
- [x] publishing dco text
- [x] configure automation to enforce DCO (on  cla=bot or similar)
- [x] Document developer requirements

Please start on this ASAP.

**Comment by mcleo-d** [comment]
Please find the FINOS Labs implementation document on Google Drive below ....

https://docs.google.com/document/d/1ZbPt7gvNXPMfCW0Tkfbd7Tq_KSfhh5VJCujas5b73dY/edit?usp=sharing

**Comment by mcleo-d** [comment]
@mindthegab, @maoo and @toshaellison - The FINOS Labs organisation has been created at https://github.com/finos-labs and configured with the information in the screenshot below ...

![screencapture-github-finos-labs-2020-09-16-13_51_04](https://user-images.githubusercontent.com/6029572/93339871-fff4d280-f823-11ea-90ec-ddf4f6adc2e3.png)

**Comment by mcleo-d** [comment]
[Probot DCO](https://probot.github.io/apps/dco/) has been configured on FINOS Labs as per the configuration demonstrated on Hyperledger Labs - https://github.com/hyperledger-labs/

## Probot DCO
![screencapture-probot-github-io-apps-dco-2020-09-16-13_51_44](https://user-images.githubusercontent.com/6029572/93340189-6aa60e00-f824-11ea-996a-4936d23c3a92.png)

## Probot DCO on Hyperledger Labs in Practice
![screencapture-github-hyperledger-labs-hyperledger-labs-github-io-pull-137-checks-2020-09-16-13_51_24](https://user-images.githubusercontent.com/6029572/93340207-709bef00-f824-11ea-8975-bf2eb6f0b812.png)

## Next Steps ...
This FINOS Labs DCO configuration will need further 'real world' testing by @mcleo-d and @maoo.

**Comment by mcleo-d** [comment]
Project Blueprint mirrored as a `private template` repo on FINOS Labs as initial placeholder for developer documentation  https://github.com/finos-labs/project-blueprint

![screencapture-github-finos-labs-project-blueprint-2020-09-16-14_20_10](https://user-images.githubusercontent.com/6029572/93343053-f53c3c80-f827-11ea-80b4-a77f086242a3.png)

**Comment by mcleo-d** [comment]
Initial DCO test on GitHub Labs Project Blueprint done, but it was realised all previous commits from the mirrored FINOS Project Blueprint need to be retrospectively signed with DCO too  ...

https://github.com/finos-labs/project-blueprint/pull/1

## DCO Failed
![screencapture-github-finos-labs-project-blueprint-pull-1-2020-09-16-14_45_45](https://user-images.githubusercontent.com/6029572/93349212-1eac9680-f82f-11ea-82d3-0c2550382eb4.png)

## DCO Retrospectively Signed with Rebase
<img width="1256" alt="Screenshot 2020-09-16 at 15 17 30" src="https://user-images.githubusercontent.com/6029572/93349761-ce820400-f82f-11ea-98a7-54eef1e34f48.png">

## DCO Passed
![screencapture-github-finos-labs-project-blueprint-pull-1-2020-09-16-15_11_43](https://user-images.githubusercontent.com/6029572/93349287-34ba5700-f82f-11ea-918d-86d17fa9e972.png)
