### ISSUE TITLE
Approve new POPs

### ISSUE THREAD

**Issue by brooklynrob** [finos/community#7]
As a follow-up to the July board approval of new PGP, which unifies the concepts of projects and working groups (into a single concept, "project), approve revised standard POP (or in the case of programs that use a custom POP, updates custom POP or move to revised standard POP. 

- [ ] DAV
- [x] DEG
- [x] DT
- [x] FDC3 (** Custom POP)
- [x] FDX
- [x] FO
- [x] Hadouken (** Used to have Custom POP; approved new standard POP on 11/1/2019)
- [x] Plexus
- [ ] Symphony (** Custom POP)
- [x] Voice ([See Vote Here](https://github.com/finos-voice/voice-program/pull/9))

**Comment by brooklynrob** [comment]
@mcleo-d Any updates from your discussions with Umesh and the Symphony program?

**Comment by brooklynrob** [comment]
@neilslinger @mcleo-d Has the revised POP (the POP approved by the board at the July 2019 board meeting) been approved by the DAV program (cc @aitana16)

**Comment by mcleo-d** [comment]
> @mcleo-d Any updates from your discussions with Umesh and the Symphony program?

Following the January 2020 board meeting, I've emailed Scott Eisenberg and Umesh Patel to propose meeting in London to discuss the Symphony program in FINOS and 2020 direction. 

I'll keep you posted on dates and outcomes.

**Comment by mcleo-d** [comment]
> @neilslinger @mcleo-d Has the revised POP (the POP approved by the board at the July 2019 board meeting) been approved by the DAV program (cc @aitana16)

During our February discussion, @mcleo-d and @neilslinger discussed Perspective activation, 
@mcleo-d meeting the Perspective team and using JPMC for events and meetups. 

POP approval by DAV was not discussed during this meeting.

**Comment by mcleo-d** [comment]
> @mcleo-d Any updates from your discussions with Umesh and the Symphony program?

Just to update, I am meeting with Scott Eisenberg and Umesh Patel on Tuesday 3rd March @ 11am in London to discuss Symphony moving into 2020.

**Comment by maoo** [comment]
This issue doesn't apply anymore, closing.
