### ISSUE TITLE
Creation of a DevOps Mutalization special interest group

### ISSUE THREAD

**Issue by mindthegab** [finos/community#74]
The work that has been ongoing at https://github.com/finos-labs/devops-mutualization and in issues in this repository https://github.com/finos/community/issues?q=is%3Aissue+is%3Aclosed+label%3Adevops-mutualization is now undergoing Board approval at the upcoming 10/21 Board meeting.

We'll post results of the vote here.

**Comment by mindthegab** [comment]
The board has approved the DevOps mutualization group at yesterday’s board meetings. Congratulations!

@mcleo-d reassigning this issue to as you work with the group to set up the SIG collaboration infrastructure.

Please before closing post here, either an issue or details as to where the SIG is progressing with onboarding and where interested contributors should go to join the group.

**Comment by mindthegab** [comment]
Congratulations to everyone involved. An area with major potential for open collaboration. Kudos! Onboarding will continue at [this issue](https://github.com/finos/community/issues/80).

@mcleo-d can you close this issue now that the groups approved and please post further details on where the continue should continue from here (repo, meeting details, etc.)

**Comment by mcleo-d** [comment]
DevOps Mutualization is currently found in https://github.com/finos-labs/devops-mutualization/ on [finos-labs](https://github.com/finos-labs/) and is being contributed to FINOS through contribution story #77  

The DevOps Mutualization leadership team is ... 
- Amol Shukla, Morgan Stanley - _SIG Lead_
- Anders Wallgren, CloudBees (@awallgren) - _SIG Secretary_

The next meeting is being scheduled for the **Week Commencing Monday 16th November**, is being organised by Amol and Anders and will be communicated shortly through FINOS and https://github.com/finos-labs/devops-mutualization/issues.
