### ISSUE TITLE
Create FINOS-Tuned/Specific Git/Github/Gitlab/MD Training 

### ISSUE THREAD

**Issue by brooklynrob** [finos/community#9]
## Potential/SuggestedTopics

* Source control: What is source control or version control? How can source control be distributed and why does it matter?
  * [External Source: git-scm ("Getting Started - About Version Control")](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control)
* What is Git?
* What does Github and Gitlab do that Git alone doesn't?
  * Github 101
     * [External Source: Github "Hello World"](https://guides.github.com/activities/hello-world/)
  * Gitlab 101
* Github Account basics (1 account for both work and personal - 1 account per heartbeat concept)
* Understanding the Github Workflow: includes an overview of branches, forks, commits, pull requests, code revision and discussion, deployment and merging.
  * Sample Pull Request workflow in FINOS context
* Alerts, notifications, and settings
* Github security vulnerability alerts
* Using Github for Product/Project/Task Management
* Markdown 101, Github Pages 101, and Documentation/Wikis Using Github
* Docusaurus basics
* The FINOS Microsite template: Using, Writing With, Administering
* How FINOS uses Github orgs and the two different models (under /finos vs. program specific github org)

## Potential External Sites/Sources to Look at/Point To
* [Git/Gitlab on Udemy](https://www.udemy.com/join/login-popup/?next=/git-expert-4-hours/learn/lecture/11685406#overview)

See too the scratchpad in [Google Docs the FINOS team](https://docs.google.com/document/d/1fn-8GchUvXLmBRlCwMco4PfdWVnvFAZHbFi_mFvNFrI/edit#) has been using to collect topics and draft content. 

NOTE: This idea is also capture in the ODP JIRA backlog as [ODP-103](https://finosfoundation.atlassian.net/browse/ODP-103)

**Comment by maoo** [comment]
No actions needed here, closing.
