### ISSUE TITLE
Community Socialisation - IoT and EdgeX for Retail Banking

### ISSUE THREAD

**Issue by dpbrookes** [finos/community#98]
## FINOS Community Socialisation
Understanding the complexity of IoT within the retail bank environment.
- Environmental complexity due to lack of interoperability
- Deployment of data-driven experiences 
- Lack of unified standards impeding digital transformation efforts
 
## Proposed Solution
Using EdgeX as middleware to provide a common open framework to enable an ecosystem of inter-changeable components and accessible data with ease and speed.

## Current State
EdgeX is the initial focus for open source contributions, with over 7M downloads across IoT verticals
 
## Existing Materials
- https://github.com/edgexfoundry
- https://www.edgexfoundry.org

**Comment by dpbrookes** [comment]
Thank you

Great call today

[cid:image002.png@01D6F4D8.6B0DFB40]

**Comment by dpbrookes** [comment]
As an example of how Intel is working through open source and collaborating with the ecosystem, please see the EdgeX Foundry webinar tomorrow https://bit.ly/3qy6EhX where Intel, IBM and HP will be discuss Open Retail Reference Architecture. This is the sort of activity I would like to get going with FINOS around Retail Banking. Thank you

**Comment by maoo** [comment]
@dpbrookes - I see that this issue haven't been updated in a while; as we don't have any hosted project in the IoT or Edge space, we can safely close this issue for now, and wait for future opportunities.

Feel free to reopen if there is any further discussion.
